### ISSUE TITLE
The icon has not enough contrast

### ISSUE THREAD

**Issue by benthillerkus** [DotBow/Blender-Launcher#10]
**Describe the bug**
The icon does not have enough contrast on grayish taskbars - which are actually not that uncommon if you have Windows auto set theme colors dependent on your desktop background.
Maybe you can go back to a more contrasty one like with _Blender Version Manager_ and / or add thin outlines.

**Screenshots**
![image](https://user-images.githubusercontent.com/29630575/83761866-288efd00-a677-11ea-871b-f55c99c8edb2.png)

**System (please complete the following information):**
 - Operation system: Windows 10 1906
 - Blender Launcher version: v1.1.0

**Comment by DotBow** [comment]
Yep, I'm not great at designing UI, will try to figure out this one.
Thanks for feedback!

**Comment by DotBow** [comment]
Added as option in settings in 1.2.0
862b90a755014332a254f33f8f22292501504646

**Comment by daephx** [comment]
The new option changes the icon of the running application but if you decide to "pin to taskbar" it does not appear to change to white on the next launch. I assume it's because windows is reading from the executables assigned icon for the start menu shortcut.

For now I'll just overwrite the shortcuts icon. It would also be cool if you could give the option for the default blender icon!

![image](https://user-images.githubusercontent.com/36192863/108184824-7d1cc000-70c0-11eb-8b1d-c6a319680831.png)

**Comment by DotBow** [comment]
> 
> 
> The new option changes the icon of the running application but if you decide to "pin to taskbar" it does not appear to change to white on the next launch. I assume it's because windows is reading from the executables assigned icon for the start menu shortcut.
> 
> For now I'll just overwrite the shortcuts icon. It would also be cool if you could give the option for the default blender icon!
> 
> ![image](https://user-images.githubusercontent.com/36192863/108184824-7d1cc000-70c0-11eb-8b1d-c6a319680831.png)

Yes, .exe and runtime icons are different for sure. Need to check if it is possible to change icon like that...

**Comment by DotBow** [comment]
About using blender icon - I don't think it is a good idea. 
Regarding to https://www.blender.org/about/logo/ it is a registered property of Blender Foundation, so it is better to use modified one:

> Prominence
> You will visualize and promote your own branding more prominent than you use the Blender logo. The Blender logo only can be used as a secondary brand, which means it has to be clear for an average viewer that this is not an official Blender or Blender Foundation website, publication or product. Do not use the Blender logo as your own logo.

I still don't really know if this is OK as it is now actually...

**Comment by daephx** [comment]
> About using blender icon - I don't think it is a good idea.
> Regarding to https://www.blender.org/about/logo/ it is a registered property of Blender Foundation, so it is better to use modified one:
> 
> > Prominence
> > You will visualize and promote your own branding more prominent than you use the Blender logo. The Blender logo only can be used as a secondary brand, which means it has to be clear for an average viewer that this is not an official Blender or Blender Foundation website, publication or product. Do not use the Blender logo as your own logo.

Understandable, a compromise to the potential legal issue could be to just allow a custom file. 
But I'd consider this is a different issue.

**Comment by DotBow** [comment]
I suppose it fixed in in v1.15.0
