### ISSUE TITLE
no build in download

### ISSUE THREAD

**Issue by adhhrg** [DotBow/Blender-Launcher#101]
windows 10
1.14.0 nothing shows in download
<img width="640" alt="Blender_Launcher_wgsGsRx1j6" src="https://user-images.githubusercontent.com/63681591/135475144-4e383dca-5191-45a6-86ab-8f4e0e8ef168.png">

**Comment by AnityEx** [comment]
same but 1.13 updating rn just in case

**Comment by DotBow** [comment]
Merging to #100
