### ISSUE TITLE
"No new Builds Available"

### ISSUE THREAD

**Issue by dshot92** [DotBow/Blender-Launcher#102]
**Describe the bug**
No new Builds Available

**To Reproduce**
1. Open Blender Launcher
2. Go to download Tab
3. See error

**Expected behavior**
I've not downloaded any new build in a couple days, i'm sure new are online, as they are available on the blender download site.

**Screenshots**
![image](https://user-images.githubusercontent.com/21959185/135659336-eb8b73c4-f995-47a8-83a9-b0b358b43b9c.png)
![image](https://user-images.githubusercontent.com/21959185/135659356-17365e23-591c-48f6-833a-e9643e219487.png)

On the site there's a 3.0a build -1st October
![image](https://user-images.githubusercontent.com/21959185/135659560-5ecc0846-8289-4768-bfe7-afc5b901e4f9.png)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.14.0 Stable
 - Log : [BL.log](https://github.com/DotBow/Blender-Launcher/files/7268927/BL.log)

**Comment by DotBow** [comment]
Merging to #100
