### ISSUE TITLE
Doesn't show any availabe builds to download

### ISSUE THREAD

**Issue by stazlincord** [DotBow/Blender-Launcher#104]
After installing to drive folder, doesn't work download tab.
Only shows "No new builds availabe".

No UAC folders and no admin rights.

System:
 - Windows 10 x64
 - Blender Launcher version: 1.14.0
 - Log file: 
[BL.log](https://github.com/DotBow/Blender-Launcher/files/7280727/BL.log)
.

**Comment by DotBow** [comment]
Merging to #100
