### ISSUE TITLE
Feature Request: Allow to change the "new builds check frequency"

### ISSUE THREAD

**Issue by xan2622** [DotBow/Blender-Launcher#114]
**Is your feature request related to a problem? Please describe.**

- Not related to a problem but for convenience, for extra customizability. 
It seems that _Blender Launcher 1.14.1_ checks for new builds avalability every 10 minutes. For different reasons, the user might want to change this setting to 15 min, 20 min, 30 min, 45 min, 1 hour, 2 hours, 6 hours...

**Describe the solution you'd like**

- Could you please add an option (in the Settings window) to let the user set the frequency of new build availability? 
By default, the input box would show "10 min", and the user could edit this value to anything else.

**Comment by DotBow** [comment]
Hi!
Thanks for feedback! Feature make sence, however user will need a button to force update builds then.

**Comment by xan2622** [comment]
A simple clickable "Check now" text in the statusbar would suffice, IMO. What do you think? 

Mock-up:
<img src="https://user-images.githubusercontent.com/1732773/144287496-ff0050f7-ee2e-482f-9f90-93f595c5f063.png" width="50%" height="50%" />

**Comment by xan2622** [comment]
Another idea: 
- Instead of showing the time of the last check,

- maybe the statusbar could display a "decreasing counter" to inform when the next check will happen
This would have the advantage to inform the user about the frequency of checks (about the delay between two checks : 10 min, 15min, 30min, 2hours ...)
<img src="https://user-images.githubusercontent.com/1732773/144303626-beeef1b0-d4f3-4bf1-85ac-3aa46123a3e7.gif" width="50%" height="50%" />

**Comment by DotBow** [comment]
Added in v1.15.0
