### ISSUE TITLE
Suggestion: remove the User tab

### ISSUE THREAD

**Issue by xan2622** [DotBow/Blender-Launcher#120]
**Is your feature request related to a problem? Please describe.**
- Currently, the "_User_" tab contains "_Favorites_" and "_Custom_" (those are located on the left side of the UI):  
IMO, their location is not consistent with the rest of the interface. IMO, there's no real need to place them inside a "User" tab.
<img src="https://user-images.githubusercontent.com/1732773/144652894-a7d45bb2-bfb2-4dd6-8412-a3d75caeefb9.png" width="75%" height="75%" />

- If you look at the BL interface (image bellow <img src="https://user-images.githubusercontent.com/1732773/144658868-e743f69e-5719-42b9-9583-7e7b56c995e7.png" width="2%" height="2%" />), it seems logical to use the left side for the type of installation: _Stable_, _Daily_, _Experimental_, (and for _Custom_) ; the top area being for "Library" and "Downloads". 
On the image above <img src="https://user-images.githubusercontent.com/1732773/144658866-b99aacab-87c0-4f72-a143-26d7dc443620.png" width="2%" height="2%" />, I think it's a bit awkward to see the "_Favorites_" tab on the left and the "Custom" tab split from "_Stable_", "_Daily_", "_Experimental_" (on the main UI).

<img src="https://user-images.githubusercontent.com/1732773/144659899-1975eef4-8492-4b31-95e0-72a42f8565b3.png" width="75%" height="75%" />

---

Here is a suggestion for a new UI (all the "types" of installations are on the left, and other tabs at the top): 

<img src="https://user-images.githubusercontent.com/1732773/144653196-88096743-f4f7-4d54-be50-592bf0e0e608.png" width="75%" height="75%" />

**Describe the solution you'd like:**
- Could you remove the "_User_" tab and move the "_Favorites_" tab to the top and the "_Custom_" tab to the left ?
- This would also save 1 click for the user: He/She would just have to click once on "Favorites" or "Custom" rather than being forced to go inside "User" tab first.

**Comment by DotBow** [comment]
Hi! 
Sound reasonable, but... then it looks like Favorites should be also in library. 
Maybe it is better to swap everything?
![изображение](https://user-images.githubusercontent.com/32243930/146691709-ff7eaa40-5ec8-494c-804d-ec1eecd99191.png)
The only problem with removing User tab is that then there is no way to sync tabs between Library and Downloads.
I think there can be a better solution to this issue

**Comment by xan2622** [comment]
> Maybe it is better to swap everything?

I have no strong opinion about swapping tabs position. Either way, it would look fine. But I tend to prefer the current layout: 
- **top:** Library, Downloads, (Favourites)
- **left:** Stable, Daily, Experimental, Custom

---

> Sound reasonable, but... then it looks like Favorites should be also in library.

I tend to think that "Favourites" should not be in "Library". To my point of view, "Favourites" doesn't belong to "Library" because is not a type of Blender installation. For me, a type of Blender is "Stable", "Daily", "Experimental" or "Custom". 

---

> The only problem with removing User tab is that then there is no way to sync tabs between Library and Downloads.

To be honest, I haven't understood the use (nor the need) to sync Library and Downloads tabs. 🤔

I have enabled "Sync Library & Download pages" in the Settings but I don't see any difference, either this checkbox is ticked or not.

You seemed to imply that there's a relation between the "User" tab and the Library & Downloads sync? How so?

**Comment by DotBow** [comment]
There is no relation between User and Library & Downloads. When you select Stable/Daily/Exp in Library it automatically sets the same page for Downloads and vice versa.
