### ISSUE TITLE
Blender Launcher no longer works

### ISSUE THREAD

**Issue by chippwalters** [DotBow/Blender-Launcher#123]
**Describe the bug**
Now, when I launch it, there is never anything "to show yet" in the Downloads tab. The "Last check" is recent and of course I can access Blender's download site on the Internet. I have no firewall or other filtering software. I am using version 1.13.0 and have installed it on a removable drive (and I tried on C: as well).

**To Reproduce**
1. Launch Blender Launcher
2. Go to taskbar icon and right-click BL icon and choose "show" 

**Expected behavior**
I have tried over a span of a few weeks and it never shows anything available for download

**Screenshots**
https://filedn.com/lLMW4jXsJqxXkRYjd1UCoKL/3d/BL-02.png
https://filedn.com/lLMW4jXsJqxXkRYjd1UCoKL/3d/BL-01.png

**System (please complete the following information):**
Windows 10 updated recently
 - Blender Launcher version: V 1.13.0
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]
 - Can't get a log file to create

**Additional context**
No other context

**Comment by xan2622** [comment]
Hi Chipp.

You seem to use an old version of Blender Launcher.

Does the problem still happen with the version 1.14.1 ?

**Comment by chippwalters** [comment]
Yay! Thanks. Back to working brilliantly! Thanks.
