### ISSUE TITLE
Feature Request: Run Blender thanks to the Command Prompt (console)

### ISSUE THREAD

**Issue by xan2622** [DotBow/Blender-Launcher#124]
**Is your feature request related to a problem? Please describe.**
- To easily read warnings, error messages and add-ons messages that can appear while using Blender (or while debugging add-ons), it's a good practice to run Blender in Command line. This way, the user can really see what's going on while using Blender or an add-on.  

- This also adds the possibility to continue using the Command Prompt after Blender has been closed.

**Describe the solution you'd like**
- Could you please 🙏 add an option to launch builds in command line?

- The [command line arguments](https://github.com/DotBow/Blender-Launcher/issues/29) (if any) would also need to be added to the command line. 

<img src="https://user-images.githubusercontent.com/1732773/144747621-0ad4167d-3ee0-4ec2-b43e-888cf5d0a53c.png" width="60%" height="60%" />

**Additional context**
- "PC Help" paragraph from this add-on website: https://hardops-manual.readthedocs.io/en/latest/issues/#helping-us-help-you
Here the developer suggests users to run Blender in command line.

- https://b3d.interplanety.org/en/how-to-check-errors-if-blender-closes-together-with-system-console-window/

- https://www.reddit.com/r/blender/comments/mp7zmw/how_do_i_run_blender_in_the_command_prompt/

**Comment by DotBow** [comment]
Hi! Do you mean open a terminal window alongside with blender?

**Comment by xan2622** [comment]
Yes, running Blender in Command Line would make Blender Launcher:

- open the Command Prompt (the console)
- enter the Blender installation folder
- run `blender.exe` in Command Line

Launching Blender this way leaves the Console window open alongside the Blender window. But this is useful because this console displays errors, warnings, ...

**Comment by DotBow** [comment]
The only way this is possible to do is to make a terminal inside BL and attach Blender to it. 
That means there will be no way to open a real console for any of the builds, instead you will be forced to use a builtin to BL.

> Yes, running Blender in Command Line would make Blender Launcher:
> 
>     * open the Command Prompt (the console/terminal)
> 
>     * enter the Blender installation folder, for example :  `cd E:\Blender_Launcher\Builds\stable\`
> 
>     * run `blender.exe` in Command Line
> 
> 
> Launching Blender this way leaves the Console window open alongside the Blender window. But this is useful because this console displays errors, warnings, ...
> 
> One could tell me that it is possible to open the terminal from Blender, but this is not the same. If the user opens the terminal from inside Blender, if Blender crashes, the terminal disappears too.
> 
> With my suggestion, the terminal stays opened whatever happens (and this is useful).
