### ISSUE TITLE
Feature Request: add options to launch Blender in debug mode

### ISSUE THREAD

**Issue by xan2622** [DotBow/Blender-Launcher#125]
**Is your feature request related to a problem? Please describe.**
- Sometimes Blender can crash. When it happens, some Blender users get frustrated because they don't always know why Blender crashed (when Blender suddenly exit without any error message). Sometimes, they even blame Blender while it can be caused by something else. 

- To know why Blender crashes, the user can run Blender thanks to the `blender_debug_log.cmd` file that is located in the Blender installation folder. Running this script opens a Command Line window, which, if Blender crashes, gives the user information about the reason of the crash (Blender itself, an add-on, out of vRAM, GPU drivers...) by generating log files with the errors. Those are located in this folder: `C:\Users\username\AppData\Local\Temp\blender\debug_logs\`

<img src="https://user-images.githubusercontent.com/1732773/144744510-e33640f2-33a7-48b0-a77c-b0963dfddbce.png" width="60%" height="60%" />

**Describe the solution you'd like:**
- Could you please 🙏 add a checkbox (on the Settings window) to launch Blender builds thanks to the `blender_debug_log.cmd` script instead of `blender.exe`? 
- As you can see on my mock-up image bellow, I have added another "Command prompt" entry to the drop-down menu. More information about this suggestion here : [github suggestion 124](https://github.com/DotBow/Blender-Launcher/issues/124). Note that these two suggestions are different, both options have different purposes. 

<img src="https://user-images.githubusercontent.com/1732773/144746700-e58f839f-f43b-4fcd-80c4-b9bb6ad31946.png" width="60%" height="60%" />

**Additional context:**
- https://docs.blender.org/manual/en/latest/troubleshooting/crash.html

**Comment by DotBow** [comment]
I did some tests, it actually possible to open a console and interact with it.
The only concern is UI - I think it is better to have those options it in RMB menu (and expose all available *.cmd commands).

**Comment by DotBow** [comment]
Added in v1.15.0
