### ISSUE TITLE
Clicking the version number button opens a broken web page

### ISSUE THREAD

**Issue by RayMairlot** [DotBow/Blender-Launcher#128]
**Describe the bug**
Clicking the version number button in Blender Launcher (i.e. the button that has "1.14.1" written on it in the status bar) opens a broken web page, instead of, what I presume is meant to be the changelog page.

The URL it opens is [https://dotbow.github.io/Blender-Launcher/changelog.html#1141](https://dotbow.github.io/Blender-Launcher/changelog.html#1141
)

**To Reproduce**
1. Click the version number button.

**Expected behavior**
The button should open the changelog page.

**Screenshots**
![Blank Blender Launcher page](https://user-images.githubusercontent.com/7059352/145084220-67655902-4be3-4c7e-97bb-694ebf7d938f.png)

**System (please complete the following information):**
 - Windows 10
 - Blender Launcher version: 1.14.1
 - Firefox 94.0.2

**Comment by xan2622** [comment]
I confirm this behaviour. It occurs here too.

**Comment by DotBow** [comment]
Thanks for report!
Fixed in #105 for 1.15.0

**Comment by DotBow** [comment]
Fixed in v1.15.0
