### ISSUE TITLE
Unable to download blender 3 stable release

### ISSUE THREAD

**Issue by saurabhgayali** [DotBow/Blender-Launcher#129]
**Describe the bug**
1. I try to download the new stable release of Blender 3 but the downloader is stuck at zero.
Related issues

**To Reproduce**
1. Go to 'Blender Launcher'
2. Click on 'Downloads' tab and choose 'Stable'.
3. Click on 'Download' in front of 3.0.0 
4. Infinite downloading

**Expected behavior**
Download should progress with update on UI

**Screenshots**
![image](https://user-images.githubusercontent.com/13806535/145844127-2b72a410-06af-4a16-b4eb-5fbb193e3d73.png)

**System (please complete the following information):**
 - Operation system:  Windows 10
 - Blender Launcher version: 1.14.1
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Additional context**
1. I already have an experimental version 3.0.1 of blender with rare addons which I have forgot installer paths, and I don't know how to update launcher keeping the list intact.
2. I have a version 2.9.3 blender stable version with various files built in that. I am unable to add it to the launcher. I also tried copying file to the paths but it doesn't work.

**Comment by DotBow** [comment]
Hi!
Does other build successfuly downloads?
Could you proved a BL.log file?

For the "additional context" part - I'm not fully understand what you are trying to achieve. Do you want to have a custom build of 2.93 inside BL? What do you mean by updating launcher?

**Comment by saurabhgayali** [comment]
1. Other version are also not downloading.
2. I do not know how to get a blog file.
3. other issues I found out that custom versions can be added, however it is also not working.

**Comment by DotBow** [comment]
> 1. Other version are also not downloading.
> 
>     2. I do not know how to get a blog file.
> 
>     3. other issues I found out that custom versions can be added, however it is also not working.

Log file will be created near by **Blender Launcher.exe** and called **BL.log**
Please, download debug version https://github.com/DotBow/Blender-Launcher/releases/download/v1.14.1/Blender_Launcher_v1.14.1_Windows_x64_DEBUG.zip and try to run it. It should show error messages if something goes wrong.
