### ISSUE TITLE
Cant set Builds-Folder on first execution

### ISSUE THREAD

**Issue by dshot92** [DotBow/Blender-Launcher#131]
**Describe the bug**
Can't use in a fresh Linux Install.
On running it shows a windows says "First, choose where Blender Builds will be stored"
On clicking continue it just exits and wont allow to choose a folder

**To Reproduce**
1. Download Linux Build
2. Extract
3. Give exectuable persmission
4. Run

**Expected behavior**
It used to show a folder selection to set the Folder for the builds

**Screenshots**
![Screenshot from 2021-12-17 00-53-55](https://user-images.githubusercontent.com/21959185/146466046-33534b4e-ff22-4d7e-8805-d196b834ab0d.png)

**System (please complete the following information):**
 - Operation system: Pop-OS 21.10
 - Blender Launcher version: Blender Launcher v1.14.1
 - Log file: Log file remains always empty

**Additional context**
Fresh linux install

**Comment by DotBow** [comment]
Hi!
Please, try to set it via terminal https://dotbow.github.io/Blender-Launcher/library_folder/#changing-library-folder

**Comment by dshot92** [comment]
it worked only when the path is specified as "./"

Any other path would not working, as it returned a problem with the permiossions.

This is really strange thoug.
I've used BL for a long time now, this is the first time it would not launche properly.

**Comment by DotBow** [comment]
> it worked only when the path is specified as "./"
> 
> Any other path would not working, as it returned a problem with the permiossions.
> 
> This is really strange thoug. I've used BL for a long time now, this is the first time it would not launche properly.

To trace an issue you should use a DEBUG build, other than that I can't help much here 😞
