### ISSUE TITLE
launch button greyed out

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [DotBow/Blender-Launcher#132]
The issue:
The launch button on all versions becomes greyed out, and right clicking does nothing after installing and re-opening the app

How to replicate:
Use KDE Plasma (Wayland) when running the command `QT_QPA_TYPE=xcb path/to/Blender\ Launcher` (with workaround)

Expected result:
Be able to press the launch button, and have a context menu pop out when right-clicking

Screenshots:
https://imgur.com/a/HzTZPVT

System:
 - Operation system: Ubuntu 21.10 with KDE Plasma 2.23.4
 - Blender Launcher version: 1.14.1 (from the releases page)
 - Log file: https://pastebin.com/hC71TbiL

**Comment by DotBow** [comment]
Hi!

Do you mean this workaround?

![изображение](https://user-images.githubusercontent.com/32243930/146635400-feaf83a9-7de2-4909-9d23-defb0f4111fa.png)

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
yes

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
wait a second it's TYPE instead of platform
