### ISSUE TITLE
.ui Files - Open Source Aspect

### ISSUE THREAD

**Issue by InfernalPlank** [DotBow/Blender-Launcher#135]
**Is your feature request related to a problem? Please describe.**
No issues! Just curious if the .ui files will ever be released. This is a unique project, and for people learning or moving into the world of PyQT, this may prove as an excellent base or excellent learning tool for further developments in Python and PyQT, as well as allowing other members of the open source community to contribute a) possible new features (like new menus) and b) possible UI bug fixes.

**Describe the solution you'd like**
Somewhere in the repo, the .ui files to be maintained, to allow community edits / contributions to the UI of the software without having to rewrite / rebuild it or tinker with it through the code itself.

**Describe alternatives you've considered**
I've looked into reversing .py into .ui, but it seems the needs for this haven't been great enough for a project to ever spawn from it. I may create a tool later, but currently lack the time to do so.

**Additional context**
The open source community relies on one another to build and improve on past and current works - if you didn't want your software to be open source, it wouldn't be on GitHub, and likewise if you didn't want community contributions, it wouldn't be on GitHub. For us to be able to fully contribute / work on this software, we are missing components (.ui files) that are necessary / vital.

**Comment by RHQ-Rusty** [comment]
It seems they were removed in [this commit](https://github.com/DotBow/Blender-Launcher/commit/b57f19e475b371f918ccf066c039becd9be267b2) (ba13c34 / b57f19e475b371f918ccf066c039becd9be267b2) on October 17, 2020.

**Comment by DotBow** [comment]
Hi!
About .ui files/
They were removed because 99% of UI is generated through code. The main reason for that is custom widgets, dynamic lists, animations etc. The rest of *_ui.py files is just a basic layout. I can't say if this is good way of making app, I'm not really a programmer and do things in my own way sometimes.
I'm a bit confused, is there any specific reason you need those?

**Comment by RHQ-Rusty** [comment]
@DotBow I appreciate the quick response!

I was simply going to suggest adding the basic .ui (core QTDesigner GUI) files in case there was a UI issue or planned update that a member of the community would like to contribute, in which case editing the code may not be the most convenient or direct approach, unless you yourself don't even use the .ui anymore and simply add / edit / change via the code directly. In that case, I suppose it would be useless for us to have UI files.

I know updating UI files and rebuilding them into .py files will remove any by-hand modifications to the .py files, so I suppose in a way it would make sense to ditch the .ui files if these modifications are done inside the .ui -> .py files directly, but as far as I can tell most changes aren't made directly to the /ui/*.py files.

**Comment by DotBow** [comment]
Well, I think the best solution is to split UI parts into separate files and make code more organized.
Designer have a lot of disadvantages for me that I faced while doing stuff related to organizing layout.
Anyway, I can't really say which way BL development turn next, I hope to overcome some of my current life issues and finally make project more mature and usable.
It's sounds like off topic but that's my answer 😅

**Comment by RHQ-Rusty** [comment]
Sounds good - take your time! Perhaps reply to or close this issue once you have UI files release or have made progress on your plans. If you're planning on entirely ditching QTDesigner, perhaps release the .ui files temporarily until the rewrite / refactor is complete if you think it is going to take a while. I hope everything goes well for you in life, as you mentioned some issues! If you'd like anything done to the repo, perhaps make a "To-Do" or "" section of the README and community members can contribute to fix / add / remove / rework, etc. for you so you can focus on life :)
