### ISSUE TITLE
Custom template subfolders

### ISSUE THREAD

**Issue by HannahCritter** [DotBow/Blender-Launcher#139]
**I am currently in love with the template function but I believe there is room for small improvements!**
Is it possible to create subfolders for the templates and select a default install template from the preferences?

**Solution**
My suggestion is to have a dropdown menu when you mouse2 over a build install and select a template based on subfolders (folder name would be the template?)
In the preferences we could then select a default template if we want to.

**Comment by DotBow** [comment]
Hi!
I also thought of this one too, it is mostly matter of proper implementation and time...
