### ISSUE TITLE
Option to use blender-launcher.exe instead of blender.exe

### ISSUE THREAD

**Issue by L0Lock** [DotBow/Blender-Launcher#140]
Since [rBf3944cf50396](https://developer.blender.org/rBf3944cf503966a93a124e389d9232d7f833c0077), there are two executables to start Blender. `blender-launcher.exe` will prevent windows' command prompt from popping out at startup.

It could be a nice addition to have the option to use that one.

**Comment by DotBow** [comment]
Hi!

It is already available via settings https://dotbow.github.io/Blender-Launcher/settings/#hide-console-on-startup-windows-only
