### ISSUE TITLE
MacOS 12.2 Monterey 

### ISSUE THREAD

**Issue by artcore-c** [DotBow/Blender-Launcher#142]
Blender is building daily on MacOS, and Apple has joined the Blender Development Fund at the time of their new M1 silicone release, a chip with graphics processing power to rival even the best eGPU… therefore it would be fitting, and especially welcome I’m sure, if a MacOS compatible version of Blender Launcher was added to the current Windows and Linux builds!

Every variation of Blender including a complete archive, experimental, branch, patch etc. can be downloaded for both Intel and Apple Silicone M1 Macs… so why not Blender Launcher?

**Comment by DotBow** [comment]
Hi! Thanks for the feedback!

Answer is pretty simple - developing on mac without having one is not very easy. I cant accelerate GPU (so no way to test BL properly), it is quite slow as well. I did attempts some time ago and the basic support is actually still here... Developing for multiple platforms as a one person is not easy.
