### ISSUE TITLE
Builds never download, just shows the processing but the bar never fills up, so no download :(  I have to manually download them from the site.

### ISSUE THREAD

**Issue by srlake31470** [DotBow/Blender-Launcher#145]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operation system: [e.g. Windows 10]
 - Blender Launcher version: [e.g. v1.0.0-rc.1]
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Additional context**

**Comment by xan2622** [comment]
Hi. 
You haven't answered any of the questions of the Issue Template. 😕 It's unfortunate because they really can help DotBow help you..

What OS do you use?
What Blender Launcher version do you use?

**Comment by srlake31470** [comment]
Version of blender launcher is 1.14.1

**Comment by srlake31470** [comment]
Windows 11 on both desktop and laptop.  It works fine on laptop,  but not
on desktop.

**Comment by srlake31470** [comment]
C:/Program Files/Blender Foundation is where the launcher points to
![image](https://user-images.githubusercontent.com/50649801/153949918-a3169b2a-bdad-4d12-87f7-733398ce4a6c.png)
![image](https://user-images.githubusercontent.com/50649801/153949976-a8f621b5-138d-46ed-ac1b-f802a17bc025.png)

I ran the debug version, and it's still just showing the downloading, but no progress bar.  
![image](https://user-images.githubusercontent.com/50649801/153950362-5168b505-40b3-4aed-b43b-210ef2becca8.png)
Not sure if this is why, whenever I uncheck it, and it runs the update, it still is checked :(.  Is this causing the issue up not being able to download from the launcher?

**Comment by DotBow** [comment]
@srlake31470 Try to change **Library Folder** to non system location, ideally non system drive.

**Comment by srlake31470** [comment]
Ok, moving it to a non system drive worked perfectly.  DOH!  Thanks.
