### ISSUE TITLE
Changelog button is not working correctly.

### ISSUE THREAD

**Issue by gadaszewski** [DotBow/Blender-Launcher#147]
After pressing the changelog button _(1.14.1)_ we are navigating to "https://dotbow.github.io/Blender-Launcher/changelog.html#1141", but the link is broken.

![image](https://user-images.githubusercontent.com/32915902/158370204-ff1991ad-38cc-4c15-8167-5dd4ef6b1ca2.png)

As we can see it's directing onto website with *.html at the end: "_dotbow.github.io/Blender-Launcher/changelog_ ****.html**** _#1141_",  think it's causing the problem, because after removing '.html' from the ending - everything is working correctly.

![image](https://user-images.githubusercontent.com/32915902/158370870-87ec2a6c-ff29-4797-a954-f41313332c55.png)

**Comment by shiena** [comment]
Probably already fixed in https://github.com/DotBow/Blender-Launcher/pull/105 but no binaries have been released.
