### ISSUE TITLE
Version and brach info missing

### ISSUE THREAD

**Issue by hsa013** [DotBow/Blender-Launcher#148]
**Describe the bug**
Version and branch columns say "Foundatio as a configuration file" instead of sg. like 3.1 stable

**To Reproduce**
Start program, see main screen.
Tried deleting the program and reinstalling it to no success.

**Expected behavior**
It should state the version and branch

**Screenshots**
![image](https://user-images.githubusercontent.com/53316416/159560858-a0fcbcc6-cf1c-4e1b-adf4-5264a5611de8.png)

**System (please complete the following information):**
 - Operation system:  Windows 10
 - Blender Launcher version: v1.14.0

**Comment by DotBow** [comment]
Hi!
Please, delete builds form Library Folder and download the [latest BL build](https://github.com/DotBow/Blender-Launcher/releases/tag/v1.14.1).

**Comment by hsa013** [comment]
sorry but this did not help

**Comment by MarkBTomlinson** [comment]
I am seeing this in 1.14.1 too.
The only place the Branch info is shown is in the Experimental Tab.
I think this is down to changes in BLenders naming convention, again, as I am also seeing a lot of dupilcate downloads, in Stable and Daily.

**Comment by DotBow** [comment]
> I am seeing this in 1.14.1 too. The only place the Branch info is shown is in the Experimental Tab. I think this is down to changes in BLenders naming convention, again, as I am also seeing a lot of dupilcate downloads, in Stable and Daily.

Hi!
Try to use latest dev build https://github.com/DotBow/Blender-Launcher/discussions/126#discussioncomment-2215817
