### ISSUE TITLE
Multiple instances of the same Blender version?

### ISSUE THREAD

**Issue by ic3D-NOB** [DotBow/Blender-Launcher#149]
**Is your feature request related to a problem? Please describe.**

I like to have multiple workflow setup for the sane Blender version and was wondering if your application would do this?
For instance I'd like to have a setup for all the addons and settings for particular workflows (hard surface modeling, animation/rigging, environmental modeling, etc) but have them all in the same version like 2.93. So I'd have several versions of 2.93 but each one setup for a particular workflow.

**Describe the solution you'd like**

To be able to click on and launch into a workflow so I wouldn't have to manually switch off/on addons and change settings as they would already be dialed in 

**Describe alternatives you've considered**

I have tried different things, I am fairly new to Blender, so I'm not sure if there is a product that would facilitate this kind of feature.
I have tried to make multiple workflows of the same version but it seems like Blender will only allow for one iteration of a version, so having separate workflow setups don't appear to be possible As far as I can tell anyway. Would you know of a way to do this? I'm a noob boob and maybe what I am thinking is unorthodox but I do want to have separate workflow setups to hopefully be more efficient

**Additional context**

I do have several addons and want to organize them into workflows if possible. Maybe in future there will be a better way of working but this seems to be something I would like to explore and wanted to know...
1) if you app can do that
2) if this would be something worth incorporating
3) any advice in possible alternatives or better ways to organize workflows

Thanks,
Brad
ic3d.sd@gmail.com

**Comment by DotBow** [comment]
Hi!
What you described is possible by using [Application Templates](https://docs.blender.org/manual/en/dev/advanced/app_templates.html).
