### ISSUE TITLE
Fails to start on Windows 11

### ISSUE THREAD

**Issue by samucacsm** [DotBow/Blender-Launcher#151]
**Describe the bug**
Cant initialize the app on my windows 11 pro realease preview pc

**To Reproduce**

**Expected behavior**
downloaded blender laucher, any version, on my windows pro 11 amd ryzen 3 processor. Extract the exe file and launch. it wont open

**Screenshots**

**System (please complete the following information):**
 - Operation system: Windows 11 Pro realease preview insider
 - Blender Launcher version: all versions
 - Log file: Cant generate

**Additional context**
thats pretty much it

**Comment by DotBow** [comment]
Hi!
Did you tried running DEBUG build? Does it produce any logs?
