### ISSUE TITLE
Pop-Up stays after closing Blender

### ISSUE THREAD

**Issue by marquismiller** [DotBow/Blender-Launcher#154]
**Describe the bug**
The codes in the command pop-up stays and there's no way of closing it. Tested in currently Blenders 3.1 and above.

**To Reproduce**
1. Go to Blender
2. Click on Close

**Expected behavior**
Blender should close with nothing left in the window tabs below or a popup.

**Screenshots**
![This is an image](https://i.imgur.com/CNki1D7.png)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.14.1

**Additional context**

**Comment by DotBow** [comment]
Hi! Thanks for report!
Not sure what exactly goes wrong, but what you see is an error trace from addons and does nothing related with BL.
