### ISSUE TITLE
Blender Launcher does not launch Blender.

### ISSUE THREAD

**Issue by creeper-0910** [DotBow/Blender-Launcher#155]
**Describe the bug**
Blender Launcher does not launch Blender.

**To Reproduce**
1. Download Blender and press the "Launch" button.
2. An orange circle will appear on the right, but will soon disappear.
3. Nothing happens.

**Expected behavior**
Blender should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/56744841/170820776-a94839c5-ac25-4785-bb97-380d12a6208b.png)

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: 1.14.1
 - Log file:

**Additional context**

**Comment by DotBow** [comment]
Hi! Thanks for report!
Try to use 1.15.0 release and let me know if issue is gone.

**Comment by That1Funguy** [comment]
I am having what seems to be the same issue. I go through the same steps.
    
     Windows 10
     1.15.0 release
I get this debug output

Failed to replace function free in module ucrtbase.dll

I do not know if it is related, but I tried downloading a different version of Blender to see if it would replicate on a newly downloaded version, but it is stuck at extracting.

**Comment by yanjingzhaisun** [comment]
> I am having what seems to be the same issue. I go through the same steps.
> 
> ```
>  Windows 10
>  1.15.0 release
> ```
> 
> I get this debug output
> 
> Failed to replace function free in module ucrtbase.dll
> 
> I do not know if it is related, but I tried downloading a different version of Blender to see if it would replicate on a newly downloaded version, but it is stuck at extracting.

same here.
win11, stuck at extracting.
