### ISSUE TITLE
Redrawing and maintaining custom folder is not complete

### ISSUE THREAD

**Issue by AntoninHS** [DotBow/Blender-Launcher#16]
Hi, 

I created a custom folder in my builds folder, and put some versions of blender in it, but the blender launcher cant find these. Is there something to do in order to get it to work?

**Comment by DotBow** [comment]
Hi!

Here is the folder layout:

<pre>
|-- %Library Folder%
    |-- custom
        |-- %custom blender build 1%
            |-- %blender.exe%
        |-- %custom blender build 1%
            |-- %blender.exe%
        |-- ...
</pre>

After that you should restart Blender Launcher, or, in [1.4.0](https://github.com/DotBow/Blender-Launcher/releases/tag/v1.4.0) you can simply got to settings and press "Reload Library Folder Content".

![изображение](https://user-images.githubusercontent.com/32243930/87880927-5dc09600-c9fe-11ea-91af-525fa37317d4.png)

**Comment by AntoninHS** [comment]
I didnt restart the program after putting my other versions. 

Thanks a lot for the update ! :)

**Comment by AntoninHS** [comment]
Ok, it turns out that the launcher cant find some of my builds

For example, I take some builds from here : https://download.blender.org/release/

And blender launcher keeps displaying "Loading build information" for these builds.

Also, when I click "reaload library folder content", it tries to reload everything. Meaning that if I had 1 build that worked in the custom folder, if I add an other, blender launcher will show me my previous build that worked, and two line with "Loading build information"
![blender](https://user-images.githubusercontent.com/38538926/87886119-c6b60700-ca1a-11ea-8e61-ba806a6cdb32.png)

**Comment by DotBow** [comment]
Yeap, bug here, still needs restart for proper redraw 😞 
It doesn't clean up custom builds information before drawing new one, will fix asap.
About 2.49b - I can guarantee support only for 2.70 and higher (at least for now).
Others will throw unexpected behavior.

**Comment by DotBow** [comment]
Fixed in [1.5.0](https://github.com/DotBow/Blender-Launcher/releases/tag/v1.5.0)
Has some WIP of auto scanning of folders, hope to finish it soon.
