### ISSUE TITLE
[Feature request] Timer for how much time have I spent in Blender.

### ISSUE THREAD

**Issue by V-isaac** [DotBow/Blender-Launcher#160]
Not sure if it was suggested or not, but i want to try it out anyway.

**Problem**
As Blender user I'd like to know how much time did i spend in it.

**Describe the solution you'd like**
As soon as I start any instance of Blender, It starts to count minutes and hours, Till the moment Blender been closed
Not sure how it would look Code-wise, Im not really a programmer myself, but I hope You'll figure it out

**Additional context**
Not really a big deal, just QOL change. Before I  even downloaded Launcher I was thinking: How much did i spend? 
There's no addon for it, neither Blender counts on its own iirc
Some people can say they've spent years in Blender, while on practice it may be just a few hours of procrastination

**Comment by xan2622** [comment]
Hi. There is an add-on: **TimeMe**
https://korchiy.gumroad.com/l/LEwkV

**Comment by DotBow** [comment]
Hi!

@xan2622 Thanks for answer!
Using add-on is a better solution because there is cases when it impossible to track if blender running.

**Comment by xan2622** [comment]
@V-isaac : I have found an even better add-on for this task (to know statistics about Blender usage): 

https://github.com/BlenderDefender/SuperEasyAnalytics
https://blenderdefender.gumroad.com/l/SuperEasyAnalytics

Enjoy :-)
