### ISSUE TITLE
Feature Request: Inclusion of UPBGE builds on launcher

### ISSUE THREAD

**Issue by xan2622** [DotBow/Blender-Launcher#164]
The Inclusion of _[bforartists](https://github.com/DotBow/Blender-Launcher/issues/119)_ builds being planned, don't you think it would make sense to also support [UPBGE](https://upbge.org/) builds as well? 

After all, there are not many other forks of Blender (that I know of), but **UPBGE** is still being [actively developed](https://github.com/UPBGE/upbge/commits/master).

> Its development cycle spans the course of 4 months: 3 months to add new features and refactors and 1 months to fix bugs. Then a new release is made available for download (around 3 or 4 per year).

Here are the download links for UPBGE:
- https://github.com/UPBGE/upbge/releases
- https://mega.nz/folder/k9MW1KiZ#UOKzjh3IQ0GEgjQ6GUc7ug/folder/dpF0VY6R

**Comment by Draise14** [comment]
Yeah, I think it's fair!
