### ISSUE TITLE
Blank Screen on Windows

### ISSUE THREAD

**Issue by iredmedia** [DotBow/Blender-Launcher#17]
**Describe the bug**
When I open it, I get a blank (resizable) window, I pressed "Cancel" when I went to select the library folder (accidentally). Assuming this may be a registry issue, though unclear.

**To Reproduce**
1. Extract to folder
2. Run program.
2. Profit.

**Expected behavior**
Unclear

**Screenshots**
https://i.imgur.com/Q70DI1x.png

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.4 & 1.37
 - Log file: No log file created

**Additional context**
None

**Comment by DotBow** [comment]
Hi!
Can reproduce on my side. 
I can't fix it right away, but the workaround is to kill all existing "Blender Launcher" processes via task manager and restart a program.

**Comment by DotBow** [comment]
Fixed in [1.5.0](https://github.com/DotBow/Blender-Launcher/releases/tag/v1.5.0)
