### ISSUE TITLE
Bforartists support

### ISSUE THREAD

**Issue by StandingPadAnimations** [DotBow/Blender-Launcher#170]
**Is your feature request related to a problem? Please describe.**
There's a very popular fork of Blender called Bforartists which is used mainly for its UI improvements. Regarding updates, it has the same problems as normal Blender 

**Describe the solution you'd like**
The ability to use Bforartists in the launcher 

**Describe alternatives you've considered**
1. Installing for each version of Blender manually
2. Downloading multiple portable zips (for people that want a local installation)

**Comment by xan2622** [comment]
Hi. It has already been requested here: https://github.com/DotBow/Blender-Launcher/issues/119
