### ISSUE TITLE
Blender Launcher.exe flagged as malicious by virustotal.com

### ISSUE THREAD

**Issue by Telumire** [DotBow/Blender-Launcher#171]
![image](https://user-images.githubusercontent.com/31185220/182096653-6cb155e8-2e05-458a-8a51-cb2f782ef4c0.png)

Here's the link to the report : 

https://www.virustotal.com/gui/file/90f7f731fb6af3a063dd89b62e3f3bf9fde8a5cb8f463d4e39b5c8bc1016e1a1/detection

**Comment by kalmdown** [comment]
I just tried to install 1.15 and Norton's says it's a virus and won't let it install.

**Comment by DotBow** [comment]
Hi!

Just add BL to antivirus exceptions.

**Comment by Telumire** [comment]
Any idea why these warnings appear ?

**Comment by kalmdown** [comment]
Why is 1.15 considered a virus, but not 1.14?

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by DotBow** [comment]
> Any idea why these warnings appear ?
@kalmdown 

Because antiviruses have whats called False Positives alarms. You can try to send an *.exe to antivirus vendor to fix an issue on their side. For more information check this thread: #43
