### ISSUE TITLE
Can't set library folder

### ISSUE THREAD

**Issue by egrajeaux** [DotBow/Blender-Launcher#173]
I'm running pop os 22.04 and just downloaded blender launcher. There is a work around for setting the library but the command doesn't seem to work on this os. maybe the syntax is different. Below is the command they suggest to use on linux:

./Blender\ Launcher -set-library-folder "%PATH%"

**Comment by DotBow** [comment]
Hi!

What path you tried to pass? Does the popup for selecting folder is shown when running from executable?

**Comment by DotBow** [comment]
> hey dotbow. that's for responding. the pop up does not uh pop up when running the executable. also when i type the command as is, the output i get is that the folder or directory doesn't exist. please excuse my ignorance but but my knowledge of syntax commands is not great.

Add desired path instead of the **%PATH%** part and it will use it as Library Folder

**Comment by DotBow** [comment]
#153

**Comment by egrajeaux** [comment]
tried setting the path and this is the output i got:
Blender Launcher: command not found

**Comment by DotBow** [comment]
> tried setting the path and this is the output i got: Blender Launcher: command not found

You should run command line from the same folder where Blender Launcher executable located.

**Comment by egrajeaux** [comment]
it's yielding the same result

**Comment by DotBow** [comment]
> it's yielding the same result

Please, take a screenshot with command and its output.

**Comment by DotBow** [comment]
> ![Screenshot from 2022-08-09 11-08-10](https://user-images.githubusercontent.com/102546039/183714026-9bb06576-2d8d-4f00-87ed-498420ca0d94.png)

Command should start with ./

**Comment by egrajeaux** [comment]
that did it. thank you
