### ISSUE TITLE
Blender Launcher update - permission error.

### ISSUE THREAD

**Issue by steve-cullum** [DotBow/Blender-Launcher#175]
**Describe the bug**
Hi, I'm seeing a permission error when trying to update to v1.15.1...I get the wait indicator, but then it just stops. Tried in admistrator mode too but get the same thing. When I've checked the log file I see this: 

2022-08-14 14:59:15,513 - Windows - Blender Launcher 1.15.0
Traceback (most recent call last):
  File "windows\main_window.py", line 485, in show_update_window
PermissionError: [Errno 13] Permission denied: 'C:/Users/steph/Desktop/Blender Launcher Updater.exe'

**To Reproduce**
1. Run Blender Launcher
2. Click on 'update to V1.15.1'
3. . Wait inicator pops up and stays there. 

**Expected behavior**
Launcher would be updated.

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: V1.15.0

**Additional context**
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9333495/Blender.Launcher.log)

**Comment by DotBow** [comment]
> **Describe the bug** Hi, I'm seeing a permission error when trying to update to v1.15.1...I get the wait indicator, but then it just stops. Tried in admistrator mode too but get the same thing. When I've checked the log file I see this:
> 
> 2022-08-14 14:59:15,513 - Windows - Blender Launcher 1.15.0 Traceback (most recent call last): File "windows\main_window.py", line 485, in show_update_window PermissionError: [Errno 13] Permission denied: 'C:/Users/steph/Desktop/Blender Launcher Updater.exe'
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Run Blender Launcher
> 
>     2. Click on 'update to V1.15.1'
> 
>     3. . Wait inicator pops up and stays there.
> 
> 
> **Expected behavior** Launcher would be updated.
> 
> **System (please complete the following information):**
> 
>     * Operation system: Windows 11
> 
>     * Blender Launcher version: V1.15.0
> 
> 
> **Additional context** Add any other context about the problem here. [Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9333495/Blender.Launcher.log)

Hi!

Try to restart OS and update again. Let me know will happen.
