### ISSUE TITLE
Feature Request: Also show release notes for Daily Builds

### ISSUE THREAD

**Issue by xan2622** [DotBow/Blender-Launcher#176]
🟦 **Is your feature request related to a problem? Please describe.**
It seems that Blender Launcher doesn't show the right-click menu "[Show Release Notes](https://wiki.blender.org/wiki/Reference/Release_Notes)" on Download > Daily Builds.

🟦 **Describe the solution you'd like**
Since the [version 1.12.0](https://github.com/DotBow/Blender-Launcher/releases/tag/v1.12.0), this feature has been added for Stable and LTS versions, but I think it would be convenient to see this menu too for Daily Builds.

🟦 **Additional context**

![Blender_Launcher_rLhc8BoTWY](https://user-images.githubusercontent.com/1732773/184660066-58606081-abe2-44be-91d5-1fc84f874bd9.gif)

**Comment by DotBow** [comment]
Hi!

Does daily builds have any release notes?..

**Comment by xan2622** [comment]
Well, not per daily build, but I thought that this page could be used:

https://wiki.blender.org/wiki/Reference/Release_Notes/3.4

**Comment by xan2622** [comment]
I have just tested your latest dev build of Blender Launcher : https://github.com/DotBow/Blender-Launcher/discussions/163#discussioncomment-3467305

I don't know what more to say than THANK YOU, DotBow. It is now possible to read the Release Notes of Daily Builds (Alpha, Betas). 👍

**Comment by xan2622** [comment]
Just one note: Would it be possible to add "Show Release Notes" when the user is on the `Downloads` > `Daily` tab ?

It works on `Downloads` > `Stable`
But it is missing on `Downloads` > `Daily`

![explorer_oq3wHpPqCb](https://user-images.githubusercontent.com/1732773/186517163-1ead8daf-ac66-4012-9002-4d03da94c80d.gif)
