### ISSUE TITLE
The neverending update (to 1.15.1)

### ISSUE THREAD

**Issue by leonard7e** [DotBow/Blender-Launcher#177]
Operating System: Ubuntu 22.04
It happened during update to 1.15.1 

The update progress bar gets stuck if it reaches the right side.
I shut down the update window. 
After I start Blender Launcher, I notice that it has been updated and Blender Launcher runs fine 

Hit 'update' in a pre-last release of Blender Launcher. (I do not know which version I used, sadly, it got overwritten during update)

After update progress bar reaches its end, stare at it and get older:
![everending_update](https://user-images.githubusercontent.com/5395270/184804193-5fce7237-c3e0-4113-9f31-d51fb04e62a9.jpg)
It won't finish.

**Comment by PyronoxO** [comment]
same problem here progress bar updating and nothing happening 
![image](https://user-images.githubusercontent.com/92161574/189486141-af1fff0a-825d-4307-ab05-56c25ae13cf4.png)

**Comment by neoOpus** [comment]
This can be fixed by removing the .ini file
