### ISSUE TITLE
"Connection Error" running under Manjaro Linux (GNOME)

### ISSUE THREAD

**Issue by willgfx** [DotBow/Blender-Launcher#18]
**Bug:**
Unable to check for builds for builds in version 1.5.0.
Status line shows "Connection Error at [time]"
Issue does not occur in version 1.4.0

**Screenshot:**
![Screenshot from 2020-08-18 19-24-18](https://user-images.githubusercontent.com/21956520/90578256-78666600-e188-11ea-948a-eb8a449b4858.png)

**System:**
 - Manjaro Linux (GNOME)
 - Blender Launcher v1.5.0
 - No log file

**Comment by DotBow** [comment]
Hi!
The connection error only happens when there is no response from blender server, so you just need to wait until everything is fine with it. Is there anything that might block connection?
I will check later on Ubuntu if everything is ok, but in 1.5 nothing was changed regarding scraping build.

**Comment by willgfx** [comment]
I always get the error in 1.5. I do not get the error in 1.4.
I am testing them one after the other.

**Comment by willgfx** [comment]
There may be a problem in your build environment. It works properly if I create my own build locally.

**Comment by DotBow** [comment]
There is new pyinstaller 4.0 released recently, maybe it fixed some of packing problems, especially with new hooks. Hope I will have time soon to look into it.

**Comment by Blenux** [comment]
Also have the same error, even after compiling it from source

![Screenshot from 2020-08-27 22-38-08](https://user-images.githubusercontent.com/25260650/91443087-2b843d00-e8b6-11ea-8ed7-3d5d05199715.png)

also i notice it was looking for things like main.py in Blender-Launcher-master\source\source, but there was no second source folder has to make it manually and also had to copy the resources folder into it also for a icon, not I'm not a coder/programmer by any means just notice it and worked it out.

**Comment by willgfx** [comment]
@Blenux The way the build script is set up, you need to run it from the project root folder, you don't need to make any folders or copy anything
`source/build_linux_singlefile.sh`

**Comment by Blenux** [comment]
Not for me

![Screenshot from 2020-08-28 00-12-05](https://user-images.githubusercontent.com/25260650/91453531-31cce600-e8c3-11ea-99aa-4ef4135db1ee.png)

**Comment by willgfx** [comment]
You're running it from the source folder, run it from one folder up.

I think i'll submit a pull request for changes to the script that will allow it to run from anywhere and still work properly.

**Comment by DotBow** [comment]
Hi @Blenux !
Trace from terminal looks like a specific issue for your GTK setup/enviromnent/missing dependencies.
Would be nice if you could run BL without building to debug and clarify if it is a packing issue or something in code.
Here is a steps for running it https://github.com/DotBow/Blender-Launcher/wiki/Development (need to add information about building too)

**Comment by Blenux** [comment]
I did what willgfx said and it work fine that way.

![Screenshot from 2020-08-28 15-57-53](https://user-images.githubusercontent.com/25260650/91526600-5cf91900-e947-11ea-88d4-4bbc9083a04d.png)

**Comment by DotBow** [comment]
@willgfx any notes on why you closed it?..

**Comment by willgfx** [comment]
Sorry about not commenting when I closed it.
I've been using my own builds for quite awhile, but this issue seems to not be an issue anymore in your builds.

**Comment by DotBow** [comment]
@Blenux could you please confirm that issue is gone?

**Comment by Blenux** [comment]
Yep working

![Screenshot_20211006_142421](https://user-images.githubusercontent.com/25260650/136135859-52cf83bb-0556-4879-9ecf-c12da2cb28da.png)

**Comment by DotBow** [comment]
Woah, so all that time the issue was with ssl certificates, interesting... Anyway, glad it fixed! Thanks for letting me know!
