### ISSUE TITLE
BforArtists support 

### ISSUE THREAD

**Issue by neoOpus** [DotBow/Blender-Launcher#189]
I think this can be easily implemented since it sufficient to make it look for bforartists.exe as well

**Comment by xan2622** [comment]
Hi @neoOpus 

There is already a "feature request" for the BforArtists implementation: https://github.com/DotBow/Blender-Launcher/issues/119

But know that DotBow recently informed us, [here](https://github.com/DotBow/Blender-Launcher/discussions/188), that the development of Blender Launcher might slow down in the future.
