### ISSUE TITLE
Social Media preview

### ISSUE THREAD

**Issue by BlenderAid** [DotBow/Blender-Launcher#19]
**Could you please put an related image to the repository's Social Media Preview**
It looks like this at the moment, which isn't really telling:
https://twitter.com/manujarvinen/status/1299687802901336066?s=20

It can be done in the repository's settings

After it's been added, it looks like this:
https://twitter.com/manujarvinen/status/1299722809409667072?s=20

Cheers!
Manu

**Comment by DotBow** [comment]
Hi!
Thanx for pointing out! Missed it when did all the setup stuff. Will change it on the next release (need to update all screenshots anyway).

**Comment by DotBow** [comment]
Added preview, don't know how much time it will take to update.
