### ISSUE TITLE
why is there no macos version?

### ISSUE THREAD

**Issue by luckychris** [DotBow/Blender-Launcher#198]
I am not sure, but it looks like there is no version for Macos, isn't it?

If it is, where can i find it?

If it isn't, why isn't it? I have a Mac and i have a some programming knowledge, maybe i can help? Is/was there a special problem why it didn't work on Macos?

**Comment by xan2622** [comment]
Here are some related *GitHub Issues* about this topic: 

https://github.com/DotBow/Blender-Launcher/issues/22
https://github.com/DotBow/Blender-Launcher/issues/61
https://github.com/DotBow/Blender-Launcher/issues/142
