### ISSUE TITLE
Win 10 - won't download Blender without running Blender Launcher as admin

### ISSUE THREAD

**Issue by LarsJandel** [DotBow/Blender-Launcher#2]
**Describe the bug**
I did run it as admin before on my laptop so the downloads worked fine, but tried it again on my workstation - not as admin.
I tried having _Blender Launcher_ at different locations:
```
C:\Program Files\Blender Foundation\Blender Launcher.exe
Desktop\Blender Launcher.exe
Documents\Blender Launcher.exe
```
The download doesn't start and I am not using any special firewalls. The download works when running _Blender Launcher_ as admin, but as you said, when launching Blender in this mode, this can trigger unexpected behaviour. For example, _Sizer_ which I use to resize windows, doesn't work anymore.
Do you have any ideas? Restarting Windows didn't help.

**To Reproduce**
1. Run Blender Launcher [NOT as admin]
2. Click on Download
3. Shows only `Downloading: 0%` - no progress

**Expected behavior**
The download should work without running _Blender Launcher_ as admin.

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: v1.0.0

**Additional context**
Thanks.

**Comment by DotBow** [comment]
Does application write something to BL.log file? What path is used for Library Folder?

**Comment by LarsJandel** [comment]
I am using the "default" Blender location as the library path:
`C:\Program Files\Blender Foundation\`
Good point, the `BL.log` file doesn't even get created in this location, but got created within _Documents_ and on the _Desktop_ and yes indeed, what you probably expected:
`PermissionError: [Errno 13] Permission denied` regarding my library path.

**Comment by DotBow** [comment]
Yes, because you are using a UAC protected folder - C:\Program Files. [It is pointed out in wiki](https://github.com/DotBow/Blender-Launcher/wiki/Installation#note-for-windows-users) that UAC protected folder will not work. Blender itself not UAC friendly.

**Comment by LarsJandel** [comment]
Ah okay, thanks. I did kinda see that and now googled it - UAC → User Account Control, as I didn't know that abbreviation. Thanks and sorry for not getting it in the first place. I will adjust it on my end. Thanks!

**Comment by DotBow** [comment]
My bad I didn't explain it well. 
Basically it means that system will corrupt every attempt to use such folders.
Of course you can try to run Blender Launcher as admin, but then it will corrupt manipulations with blender.exe.
So it is kind of limitation right now, maybe in future I will find a way to manage it.
