### ISSUE TITLE
Manage Updates to Blender Launcher aswell

### ISSUE THREAD

**Issue by benthillerkus** [DotBow/Blender-Launcher#20]
**Is your feature request related to a problem? Please describe.**
Right now Blender Launcher is getting rather frequent updates - and updating Blender Launcher involves some clicking for getting the auto start stuff to work. It's annoying enough to keep you from updating when the current version already works.

**Describe the solution you'd like**
I'd propose that Blender Launcher should manage and install updates for Blender Launcher.

**Describe alternatives you've considered**
Maybe some kind of installer that automatically overwrites the old version.

**Comment by DotBow** [comment]
Hi! 
Thank for suggestion, I'm already working on it 🙂

**Comment by DotBow** [comment]
Added to [Blender Launcher 1.6.0](https://github.com/DotBow/Blender-Launcher/releases/tag/v1.6.0)
