### ISSUE TITLE
Option to create a config folder in the extracted 3.* folder instead of on the system.

### ISSUE THREAD

**Issue by imperfectlink** [DotBow/Blender-Launcher#201]
**Is your feature request related to a problem? Please describe.**
I like to have my portable version of Blender be truly portable and have the config folder be in the version folder. Eg. blender-3.4.0-windows-x64/3.4/config

**Describe the solution you'd like**
Add an option to always store configs there instead of in the roaming data. I usually do this manually byu creating a config folder before starting up a fresh extracted Blender.

**Additional context**

**Comment by xan2622** [comment]
Hi @imperfectlink
I have also requested this feature here: https://github.com/DotBow/Blender-Launcher/issues/116
