### ISSUE TITLE
Blender Launcher crashes on PopOS 22.04 LTS, upon launch after fresh download.

### ISSUE THREAD

**Issue by Syed-Taha-0** [DotBow/Blender-Launcher#202]
The blender launcher app crashes when trying to run the app on PopOS (22.04 LTS)

**To Reproduce** (on PopOS 22.04 LTS)
1. Download the latest release for Linux.
3. Extract the compressed archive, and run the executable file within.
4. As this is the first time running, the application should ask for the path to library.
5. Click "Continue".
6. The app crashes.
7. This keeps on happening, every time the application is executed.

**Expected behavior**
The application should have allowed me to select the library location and then run normally.

**Screenshots**
![Screenshot from 2022-12-11 20-25-46](https://user-images.githubusercontent.com/109780459/206910909-0cb8ac60-17b1-4b48-aa30-949b62ca7340.png)

**System (please complete the following information):**
 - Operation system: PopOS 22.04 LTS
 - Blender Launcher version: 1.15.0
 - Log file: [Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/10202476/Blender.Launcher.log)

**Additional context**
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/10202476/Blender.Launcher.log)

The launcher was working fine on Endeavour OS (arch-based distro) the other day.

**Comment by Phildor92** [comment]
For what it's worth, I get the same errors with the same distro and version

**Comment by Syed-Taha-0** [comment]
It would be real nice if the authors of the program could fix this issue, I use blender and would be grateful!

**Comment by henrythasler** [comment]
Same behavior for Ubuntu 22.04.1 LTS:
```
$ ./'Blender Launcher' 
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

(Blender Launcher:12333): Gtk-WARNING **: 18:06:39.964: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```
Not sure about the additional swrast error...

**Comment by LoganX83** [comment]
Same here with Manjaro XFCE Edition. Works on KDE Edition.

`
import 'ui.update_window_ui' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f87fd3bb760>
import 'windows.update_window' # <_frozen_importlib_external.SourcelessFileLoader object at 0x7f87fd3bb4c0>
Gtk-Message: 09:34:17.142: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:34:17.142: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:34:17.142: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:34:17.143: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/_MEIo2ll9p/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/_MEIo2ll9p/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /tmp/_MEIo2ll9p/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
import 'gc' # <class '_frozen_importlib.BuiltinImporter'>

(Blender Launcher:9163): Gtk-WARNING **: 09:34:19.380: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Format der Bilddatei unbekannt (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Format der Bilddatei unbekannt (gdk-pixbuf-error-quark, 3)
[9162] LOADER: Restoring signal handlers
[9162] LOADER: freeing args
[9162] LOADER: child received signal 6; storing for re-raise after cleanup...
[9162] LOADER: Back to parent (RC: 1)
[9162] LOADER: Doing cleanup
[9162] LOADER: Freeing archive status for /home/logan/Applications/Blender Launcher
[9162] LOADER: re-raising child signal 6
zsh: IOT instruction (core dumped)  ./Blender\ Launcher
`

**Comment by dyargici** [comment]
10 months later and I have the same issue.  Is this still in development?  Would be nice if it was just an AppImage tbh.

Pop!_OS 22.04 LTS
