### ISSUE TITLE
A feature to easily import/export config and addons from one version to another would be nice. THanks!

### ISSUE THREAD

**Issue by IGjvliveh** [DotBow/Blender-Launcher#207]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xan2622** [comment]
I second this suggestion. 👍

Now that [Blender Launcher 1.16.0-dev](https://github.com/DotBow/Blender-Launcher/discussions/163#discussioncomment-3530477) has been released with the ability to [make builds really portable](https://github.com/DotBow/Blender-Launcher/issues/116), it would make sense and would be very convenient to be able to copy the preferences (config files, addons, keymaps, ...) from a build to another.

Here is a mock-up that shows what the menu could look like: 
- Right-clicking on a build would allow to `Copy Preferences` (here, from Blender 3.3.2)

![copy](https://user-images.githubusercontent.com/1732773/209717557-1ddc6f5a-0cd8-46a4-9b0c-884ffe22b5ed.png)


- Then, on the target build, the user would be able to `Paste Preferences` (to Blender 3.4.1)

![paste](https://user-images.githubusercontent.com/1732773/209717568-f76a6514-d89c-4034-bbaf-d198c04f011f.png)

**Comment by builder-main** [comment]
This is definitelly much needed. Now is there a way to do this task manually in the meantime ?
