### ISSUE TITLE
Resume interrupted downloads

### ISSUE THREAD

**Issue by madjama** [DotBow/Blender-Launcher#208]
I have a unstable internet connection, and my downloads is commonly interrupted. Blender Launcher appears to be unable to resume a (almost completed) download, instead I have to download with a web-browser.

It would be very nice if Blender Launcher had the ability to resume interrupted downloads, like one can with downloads in a web-browser.

Currently I can download Blender thru a browser instead and add it as a custom build, at least this way Blender Launcher handles transferring my configuration, and eases the process of deleting it later.

**Comment by xan2622** [comment]
This is an interesting idea.  👍
It would also help when there are new official Blender releases : it's common to notice [slow downloads](https://github.com/DotBow/Blender-Launcher/discussions/199).
