### ISSUE TITLE
Auto close when downloading latest blender

### ISSUE THREAD

**Issue by jecevanski** [DotBow/Blender-Launcher#209]
**Describe the bug**
Its stuck in this state then after a brief period time it auto closes 

**Screenshots**
![image](https://user-images.githubusercontent.com/71339421/209971861-de0589db-459c-468a-8125-8b8c9716635a.png)

**Comment by xan2622** [comment]
Hi. 
Does this behaviour (*Blender Launcher* being stuck, then closes) still happens with the latest [1.16.0 dev" build](https://github.com/DotBow/Blender-Launcher/discussions/163#discussioncomment-3530477) ?

On a side note, just know that *Blender Launcher* is no longer being actively developed. https://github.com/DotBow/Blender-Launcher/discussions/188 (sadly, we can't expect many bug fixes from DotBow from now on, maybe one day?)
