### ISSUE TITLE
Can't launch Blenders from the app (but the Blenders downloaded with this app do work)

### ISSUE THREAD

**Issue by manujarvinen** [DotBow/Blender-Launcher#21]
**Describe the bug**
- I'm using Xubuntu 19.10
- Can't launch Blenders from the app. When I click 'Launch' on a downloaded Blender, the '1' icon (that means 1 Blender is running) appears for a while, then just disappears. Nothing else happens.
- However, the Blenders downloaded with this app do work, when I go to the folder they're downloaded in
- Also in my other system this app works as it should (Pop!_OS 20.04 LTS)

**System (please complete the following information):**
 - Operation system: Xubuntu 19.10
 - Blender Launcher version: 1.5.0
 - Log file: attached
(although, now that I removed everything and re-extracted the launcher, it doesn't generate a log file anymore, but the issue remains)
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/5305458/Blender.Launcher.log)

**Comment by DotBow** [comment]
Hi! Thanks for report!

I will fix the issue from log file, however it is not related to failure of executing Blender.
Could you try to run BL from bash or use previous release?

Would be nice to also run and see if this command fails:

`nohup %path to blender executable%`

**Comment by manujarvinen** [comment]
Hi!

Thanks for being so fast to respond :)

Both commands work, running Blender from bash and also the nohup one

nohup yielded this message:
mj@Z800:~$ nohup /home/mj/Downloads/Blenders/stable/blender-2.90.1-linux64/blender
nohup: ignoring input and appending output to 'nohup.out'
mj@Z800:~$ 

I don't know where the nohup.out is located, so I can't include it to this message.

Thanks!

**Comment by DotBow** [comment]
When running BL from bash you can see more information on whats happening while you are using it (trace possible errors).
Command nohup should run blender... it only shows the message?

**Comment by manujarvinen** [comment]
Yeah, I think there's nothing wrong with the Blenders themselves...

____________________________
manujarvinen.com <http://www.manujarvinen.com> | @manujarvinen
<https://twitter.com/manujarvinen>

**Comment by DotBow** [comment]
Hi!
You can try the latest build with couple of fixes and updated packages, maybe it will solve the problem:
https://drive.google.com/file/d/1IqO-4KeAT7jMpd1b47dcFFsJ6BkNtHf-/view?usp=sharing

**Comment by manujarvinen** [comment]
Oh man! False alert all of this (in a way)

I had some issue of not the program showing, but its tray icon was showing, and I could launch the launcher via that. I also rebooted the computer and launched again and after 15-20 seconds the launcher fully opened up. Maybe I was just too anxious to get it running immediately and was closing it with task manager before it even opened :/

The latest dev build you gave behaved just the same way.

I just need to be more patient (or... if that 15-20sec startup time could be reduced somehow...)

Sorry to be wasting your time :(

All is good :)

**Comment by DotBow** [comment]
It might be OS related when BL needed to be build for each of distributions exclusively (which is kind of pain).
For now I use only Ubuntu for Linux builds, it seems that there is something with Debian based difference here.

**Comment by manujarvinen** [comment]
Okay, too bad :/

Well, but I can throw Pop!_OS to my second computer as well, next time I
update. For now Blender Launcher is good for downloading the different
Blenders, I just need to launch them manually.

Thanks for everything :)

Cheers!

Manu

____________________________
manujarvinen.com <http://www.manujarvinen.com> | @manujarvinen
<https://twitter.com/manujarvinen>

**Comment by DotBow** [comment]
I will try to manage and build on a wider range of distros, however it is take time as well as adds some complexity to update system. 
Hope there is some workaround for this as well.

**Comment by DotBow** [comment]
Hi!
Please, check this build:
https://drive.google.com/file/d/1udvGLdbqpQYLBFUyR7Tyl1UrDNdUE7A7/view?usp=sharing

**Comment by manujarvinen** [comment]
> Hi!
> Please, check this build:
> https://drive.google.com/file/d/1udvGLdbqpQYLBFUyR7Tyl1UrDNdUE7A7/view?usp=sharing

Same issue :/ Can't launch Blenders with it (in my second computer). But it opens up very quickly, no more of that date error log file.

**Comment by DotBow** [comment]
Sorry for having such trouble, you can check another one https://github.com/DotBow/Blender-Launcher/issues/24#issuecomment-709573868

**Comment by DotBow** [comment]
I will close this issue and continue investigating it on #24, thanks for report!
