### ISSUE TITLE
Detect currently installed blender versions

### ISSUE THREAD

**Issue by Dane411** [DotBow/Blender-Launcher#214]
I came across your app when trying to find an app to manage my currently installed blender versions.
I've been updating with Winget/Chocolatey and they just install the new version without removing the old one, which ends up taking a lot of disk space.

The app firstly prompted to provide the install directory, so I picked C:\Program Files\Blender Foundation, root folder where all the versions are, however it didn't detect that I already had 7 versions installed.

**Comment by xan2622** [comment]
Hi Dane411.

To make *Blender Launcher* detect your other Blender installations, they have to be placed in the "custom" folder.
https://dotbow.github.io/Blender-Launcher/library_folder/#structure

Then, they will appear in Blender Launcher, inside `User > Custom` tabs.
