### ISSUE TITLE
Make an option to add the Asset Library to every blender instance

### ISSUE THREAD

**Issue by PascalSchimmler** [DotBow/Blender-Launcher#224]
**Is your feature request related to a problem? Please describe.**
It is annoying to download a new version and having the set the asset library path

**Describe the solution you'd like**
A path you can select to the asset library that gets set for every downloaded blender instance 

**Describe alternatives you've considered**
None.

**Comment by thinsoldier** [comment]
It would be better if Blender itself had a feature to export the current list of asset library paths as a bit of python code that you can then run in the other Blender builds. If they had that feature it would make it quite easy for Blender-Launcher to automate applying that list to all the downloaded builds for you.
