### ISSUE TITLE
Portable config folder per version

### ISSUE THREAD

**Issue by HowieDuhzit** [DotBow/Blender-Launcher#229]
**Is your feature request related to a problem? Please describe.**
Sometimes I like to make my versions config files isolated from each other instead of using the appdata folder for them

**Describe the solution you'd like**
An option to make the version you install save its configs in its own folder

**Describe alternatives you've considered**
I currently have to browse to the folder for the version and manually add the config folder

**Additional context**
that is all its pretty simple all things considered

**Comment by xan2622** [comment]
This option has already been added to Blender Launcher 1.16.0-dev :  https://github.com/DotBow/Blender-Launcher/discussions/163
