### ISSUE TITLE
Granular notification settings

### ISSUE THREAD

**Issue by antoson** [DotBow/Blender-Launcher#23]
**Is your feature request related to a problem? Please describe.**
I'd like to disable notifications for new available builds but still get notifications for finished downloads.

**Describe the solution you'd like**
Add notifications section in settings.

**Describe alternatives you've considered**
Currently, I've blocked notifications for Blender Launcher in Windows Action center, but this disables *all* notifications.

**Additional context**
Draft of new settings window:
![mockup](https://user-images.githubusercontent.com/36371990/95318449-debd5a00-0896-11eb-81df-ccaf8a289168.jpg)

I also want to extend my thanks for developing this great and useful tool.

**Comment by DotBow** [comment]
Added to [Blender Launcher 1.6.0](https://github.com/DotBow/Blender-Launcher/releases/tag/v1.6.0)
