### ISSUE TITLE
Winget package

### ISSUE THREAD

**Issue by GreenMan36** [DotBow/Blender-Launcher#230]
**Describe the solution you'd like**
I'd like to be able to do `winget install dotbow.blender-launcher` and get the app via winget.

**Describe alternatives you've considered**
Chocolatey is nice, but it doesn't have a package either.

**Additional context**
Blender IS available via winget but this project is just too good.

**Comment by babo4d** [comment]
It is available from [scoop](https://scoop.sh/).

https://scoop.sh/#/apps?q=blender&id=15c5f60f97409026847d2de9890a9cb20e50e25f
