### ISSUE TITLE
Is this a bug I can't see any 4.1 builds under Daily or Experimental?

### ISSUE THREAD

**Issue by dener3id** [DotBow/Blender-Launcher#242]
**Describe the bug**

**To Reproduce**
1. Go to Open App and after allowing to sync to servers no builds shown under daily and experimental. 

**Expected behavior**
Fails to show any dev or experimental builds.

**Screenshots**
![Screenshot_2023-11-16_14-59-55](https://github.com/DotBow/Blender-Launcher/assets/43898930/8703eaa5-469b-4406-819d-5b532963549b)
![Screenshot_2023-11-16_15-00-37](https://github.com/DotBow/Blender-Launcher/assets/43898930/6ddc38d1-4b35-409c-a7b6-6a97ee099140)
![Screenshot_2023-11-16_15-01-04](https://github.com/DotBow/Blender-Launcher/assets/43898930/df7c6dae-2bd5-47d7-98e5-e951f53f199b)

**Can no longer download this or see any new updates to the build as they should be auto each 24 hours.**
![4 1 de ](https://github.com/DotBow/Blender-Launcher/assets/43898930/ffe18588-3596-48a4-96cf-c5682284cf7d)

**System**
 - Operation system: Linux Mint 21.2
 - Blender Launcher version: 1.15.1
 - Log file: [Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/13384552/Blender.Launcher.log)

**Comment by JJeris** [comment]
The app is abandoned, but anyways, Blender.org changed its download UI, which means BL webscraping the download links no longer works.

**Comment by drpsyko101** [comment]
Yup, this issue has been raised in #241. I truly wish someone would've picked up this awesome tool. Unfortunately I do not have much expertise in Python.

**Comment by dener3id** [comment]
Now it just hangs on downloading is there another tool for this I'm sick of updating the lts versions?

**Comment by L0Lock** [comment]
https://twitter.com/tonroosendaal/status/1726565669590986932

It might be why

**Comment by Victor-IX** [comment]
You can download a fix version here:
https://github.com/Victor-IX/Blender-Launcher/releases/tag/v1.15.2
