### ISSUE TITLE
Blender Launcher (any version) does not show any builds to download

### ISSUE THREAD

**Issue by ChellWilliwaw** [DotBow/Blender-Launcher#244]
Not really a bug, but I need help.
I start the Blender Launcher and check for new builds, but none appear. Not even in the experimental Tab.
Weirdly this happens with all verrsions of Blender Launcher that I download. Am I doing something wrong? 

Normally there should be multiple versions of Blender appear for us to download
![46fa7aa7e8b9f4171c0f620e46ec607182c65b35](https://github.com/DotBow/Blender-Launcher/assets/151009470/d134eb75-9095-4cdd-909d-f4d029578c3d)

but this is how it looks for me.
![Screenshot 2023-11-22 091701](https://github.com/DotBow/Blender-Launcher/assets/151009470/70863d2f-fe24-44be-adeb-664b785023af)

![Screenshot 2023-11-22 0922032](https://github.com/DotBow/Blender-Launcher/assets/151009470/3c802733-7e09-4884-b840-8c529ac34138)

I am wondering where I could have messed up, cause the only step I need to do when Installing is to chose a downloads folder.

 - Operation system: Windows 10
 - Blender Launcher version: 1.15.1

**Comment by ValentinN84** [comment]
Blender.org is experiencing a DDOS attack these days so their servers are not responding in a timely manner. \
Personally I'm having trouble accessing the site and the online documentation.

**Comment by xan2622** [comment]
It has already been reported (in https://github.com/DotBow/Blender-Launcher/issues/241 and https://github.com/DotBow/Blender-Launcher/issues/242 and also here: https://github.com/DotBow/Blender-Launcher/discussions/243).

If you can't find the Stable builds, it's because there's an ongoing DDOS attack on the official Blender websites.
It is currently being fixed by the Blender team. When the websites are back online, you should regain access to the Stable builds in Blender Launcher. 

But don't expect much to see any Experimental or Daily builds from now on in *Blender Launcher*, the https://builder.blender.org/download/daily/ page has recently changed and now *Blender Launcher* can't "find" the daily builds anymore. 

And regarding a possible fix from the *Blender Launcher* developer, DotBow mentioned [here](https://github.com/DotBow/Blender-Launcher/discussions/188), that all development regarding *Blender Launcher* has stopped.

**Comment by xan2622** [comment]
> and the online documentation.

The documentation is accessible (but slower) from: https://web.archive.org/web/20231120205935/https://docs.blender.org/manual/en/latest/

**Comment by Victor-IX** [comment]
You can download a fix version here:
https://github.com/Victor-IX/Blender-Launcher/releases/tag/v1.15.2

**Comment by L0Lock** [comment]
It seems to work only partially:

![2023-11-24_16h17_Blender_Launcher_1046](https://github.com/DotBow/Blender-Launcher/assets/16049822/33a76207-f065-4ff1-a731-52bfc34f1712)

No stable releases and only a few experimentals (with no description) and dailies.

**Comment by Victor-IX** [comment]
> It seems to work only partially:
> 
> ![2023-11-24_16h17_Blender_Launcher_1046](https://private-user-images.githubusercontent.com/16049822/285544957-33a76207-f065-4ff1-a731-52bfc34f1712.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjExNDgsIm5iZiI6MTcwMDg2MDg0OCwicGF0aCI6Ii8xNjA0OTgyMi8yODU1NDQ5NTctMzNhNzYyMDctZjA2NS00ZmYxLWE3MzEtNTJiZmMzNGYxNzEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIxMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ODc0YTdjY2ZjZjZjZGViOTI4MGNmMmZmMjQzY2RmNTUzOWFlNDdlOWUwNDM2ZTY0YjFmMzg1NGI0MTVmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TW6JJJL_u-MDqA308rhMbzH6WD8sgrEJvKJhDnCGE5I) [ ![2023-11-24_16h17_Blender_Launcher_1046](https://private-user-images.githubusercontent.com/16049822/285544957-33a76207-f065-4ff1-a731-52bfc34f1712.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjExNDgsIm5iZiI6MTcwMDg2MDg0OCwicGF0aCI6Ii8xNjA0OTgyMi8yODU1NDQ5NTctMzNhNzYyMDctZjA2NS00ZmYxLWE3MzEtNTJiZmMzNGYxNzEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIxMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ODc0YTdjY2ZjZjZjZGViOTI4MGNmMmZmMjQzY2RmNTUzOWFlNDdlOWUwNDM2ZTY0YjFmMzg1NGI0MTVmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TW6JJJL_u-MDqA308rhMbzH6WD8sgrEJvKJhDnCGE5I) ](https://private-user-images.githubusercontent.com/16049822/285544957-33a76207-f065-4ff1-a731-52bfc34f1712.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjExNDgsIm5iZiI6MTcwMDg2MDg0OCwicGF0aCI6Ii8xNjA0OTgyMi8yODU1NDQ5NTctMzNhNzYyMDctZjA2NS00ZmYxLWE3MzEtNTJiZmMzNGYxNzEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIxMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ODc0YTdjY2ZjZjZjZGViOTI4MGNmMmZmMjQzY2RmNTUzOWFlNDdlOWUwNDM2ZTY0YjFmMzg1NGI0MTVmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TW6JJJL_u-MDqA308rhMbzH6WD8sgrEJvKJhDnCGE5I) [ ](https://private-user-images.githubusercontent.com/16049822/285544957-33a76207-f065-4ff1-a731-52bfc34f1712.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjExNDgsIm5iZiI6MTcwMDg2MDg0OCwicGF0aCI6Ii8xNjA0OTgyMi8yODU1NDQ5NTctMzNhNzYyMDctZjA2NS00ZmYxLWE3MzEtNTJiZmMzNGYxNzEyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIxMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ODc0YTdjY2ZjZjZjZGViOTI4MGNmMmZmMjQzY2RmNTUzOWFlNDdlOWUwNDM2ZTY0YjFmMzg1NGI0MTVmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TW6JJJL_u-MDqA308rhMbzH6WD8sgrEJvKJhDnCGE5I)
> 
> No stable releases and only a few experimentals (with no description) and dailies.

For issues related to the version I've made please report them on the fork project: https://github.com/Victor-IX/Blender-Launcher/issues

**Comment by Victor-IX** [comment]
@L0Lock  Go check --> https://github.com/DotBow/Blender-Launcher/issues/245#issuecomment-1826387767
