### ISSUE TITLE
No new builds available in Downloads

### ISSUE THREAD

**Issue by mikafill** [DotBow/Blender-Launcher#245]
**Describe the bug**
After installing Blender Launcher and created a library folder on Windows, I cannot download any version of blender from the download section. The message "no new builds available" appears. I try to Check again it doesn't change anything. I also tried to reinstall Blender Launcher it doesn't solve the issue.

**To Reproduce**
1. Go to 'Downloads'
_2. Click on '....'
4. See error_

**Expected behavior**
The different versions of Blender should appears

**Screenshots**
![Capture](https://github.com/DotBow/Blender-Launcher/assets/109593187/a8953e62-97a4-4483-9e77-c5bb08305fa8)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.15.0
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Additional context**

**Comment by MaMOgithub** [comment]
same problem here

**Comment by Victor-IX** [comment]
Link to #241 #244 #242

**Comment by Victor-IX** [comment]
You can download a fix version here:
https://github.com/Victor-IX/Blender-Launcher/releases/tag/v1.15.2

**Comment by sensenku** [comment]
Hi, thank you for fixing, but Stable Download version is not available :)

![image](https://github.com/DotBow/Blender-Launcher/assets/16852177/5cf49365-239e-44ed-812d-25cb3681cfdd)

**Comment by Victor-IX** [comment]
@sensenku Stable builds are not available for now on any version and I can't do anything about it, the web requests are currently blocked by the Blender Foundation, I'm reaching out to them to see what we can do to fix that without creating too much load on the server.

PS: if you have a bug on the fork version I made please report the issue on the forked project, not this one:
https://github.com/Victor-IX/Blender-Launcher/issues
