### ISSUE TITLE
Favorites tab

### ISSUE THREAD

**Issue by Iglum** [DotBow/Blender-Launcher#26]
Can we get a favorites tab so i find and test different versions of Blender more easy. 👍
or the possibility to just make a custom tab to have a collection with Blender executables.

**Comment by DotBow** [comment]
Hi!
Sounds interesting, but can't promise anything thought.
Will see if I have time to check what can be done.

**Comment by DotBow** [comment]
Implemented in 1.10.0 https://github.com/DotBow/Blender-Launcher/releases/v1.10.0
