### ISSUE TITLE
Fontconfig error running under Antergos Linux (Arch)

### ISSUE THREAD

**Issue by Quijx** [DotBow/Blender-Launcher#27]
**Describe the bug**
When I try to run the `Blender Launcher` file using the console, the following error is shown and no window is opened:
```
> ./Blender\ Launcher
QApplication: invalid style override 'gtk' passed, ignoring it.
        Available styles: Windows, Fusion
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
Fontconfig warning: FcPattern object weight does not accept value [0 14.8)
Segmentation fault (core dumped)
```
Here my `/etc/fonts/fonts.conf` file, as this error seems to be related to that:
<details>
<summary>/etc/fonts/fonts.conf</summary>

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- /etc/fonts/fonts.conf file to configure system font access -->
<fontconfig>
	<its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
		<its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
	</its:rules>

	<description>Default configuration file</description>

<!--
	DO NOT EDIT THIS FILE.
	IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
	LOCAL CHANGES BELONG IN 'local.conf'.

	The intent of this standard configuration file is to be adequate for
	most environments.  If you have a reasonably normal environment and
	have found problems with this configuration, they are probably
	things that others will also want fixed.  Please submit any
	problems to the fontconfig bugzilla system located at fontconfig.org

	Note that the normal 'make install' procedure for fontconfig is to
	replace any existing fonts.conf file with the new version.  Place
	any local customizations in local.conf which this file references.

	Keith Packard
-->

<!-- Font directory list -->

	<dir>/usr/share/fonts</dir>
	<dir>/usr/local/share/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<!-- the following element will be removed in the future -->
	<dir>~/.fonts</dir>

<!--
  Accept deprecated 'mono' alias, replacing it with 'monospace'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>mono</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>monospace</string>
		</edit>
	</match>

<!--
  Accept alternate 'sans serif' spelling, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans serif</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

<!--
  Accept deprecated 'sans' alias, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>
<!--
  Accept alternate 'system ui' spelling, replacing it with 'system-ui'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>system ui</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>system-ui</string>
		</edit>
	</match>

<!--
  Load local system customization file
-->
	<include ignore_missing="yes">conf.d</include>

<!-- Font cache directory list -->

	<cachedir>/var/cache/fontconfig</cachedir>
	<cachedir prefix="xdg">fontconfig</cachedir>
	<!-- the following element will be removed in the future -->
	<cachedir>~/.fontconfig</cachedir>

	<config>
<!--
  Rescan configuration every 30 seconds when FcFontSetList is called
 -->
		<rescan>
			<int>30</int>
		</rescan>
	</config>

</fontconfig>

```
</details>

Also, here the zipped core dump file created by `coredumpctl dump 6801 -o Blender_Launcher_dump` where `6801` is the PID of the run that I found using `coredumpctl list`:

[Blender_Launcher_dump.zip](https://github.com/DotBow/Blender-Launcher/files/5540920/Blender_Launcher_dump.zip)

**Expected behavior**
Blender-Launcher starts normally.

**System (please complete the following information):**
 - Operation system: Antergos Linux (Arch)
    - Antergos Linux (Arch)
    - KDE Plasma Version: 5.19.5
    - KDE Frameworks Version: 5.73.0
    - Qt Version: 5.15.0
    - Kernel Version: 5.8.5-arch1-1
    - OS Type: 64-bit
 - Blender Launcher version: v1.7.1
 - Log file: Probably not generated yet.

**Comment by DotBow** [comment]
Hi!
This one is a hard catching bug...

Could you please try this if this command fixes the issue (installing fonts):
`sudo fc-cache -f -v`

You can also try to clean up the font cache:
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by Quijx** [comment]
I tried both and restarted my pc. Did not work. Still the same errors as before.

**Comment by DotBow** [comment]
Sorry for having troubles with running BL, trying to found out the breaking point.
What is funny, it runs even without **fonts.conf** file perfectly on my side 🙃

**Comment by Quijx** [comment]
Without console, just nothing happens when i click the file. I just used the console so that I at least get an error. I'll try a system upgrade next. Maybe the `fonts.conf` is indeed outdated. I rarely do system upgrades, cause something always breaks :grin:. If that doesn't work I'll mess around with the `fonts.conf` and maybe try yours. We'll see.

**Comment by DotBow** [comment]
> Without console, just nothing happens when i click the file. I just used the console so that I at least get an error. I'll try a system upgrade next. Maybe the `fonts.conf` is indeed outdated. I rarely do system upgrades, cause something always breaks 😁. If that doesn't work I'll mess around with the `fonts.conf` and maybe try yours. We'll see.

Oh, I see. Anyway, that's still looks like something environment related (on my side or yours, doesn't really matter for now). 
I didn't find much of a useful information, but this issue happens with QT in wide range of apps.
I will look for more information tomorrow, sorry for headache 🤕 
You can try to build BL by yourself using [instructions](https://github.com/DotBow/Blender-Launcher/wiki/Development) from wiki or update/use other distro for the meantime.

**Comment by DotBow** [comment]
By the way - since BL successfully running even with fontconfig error on my side (it doesn't crash the program), I assume this is related to something else.

**Comment by DotBow** [comment]
About core dump file - it doesn't seem to contain something useful.
You could try to run this for debug:
`gdb ./Blender\ Launcher`
And then:
`run
`

**Comment by Puncia** [comment]
FYI I had the same problem on Fedora 34. The problem appears to be the version of fontconfig BL is compiled against.
Building BL locally using `build_linux.sh` fixes the issue for me.

**Comment by DotBow** [comment]
> 
> 
> FYI I had the same problem on Fedora 34. The problem appears to be the version of fontconfig BL is compiled against.
> Building BL locally using `build_linux.sh` fixes the issue for me.

Still no clue how to build with a "generic" fontconfig... Will see how it goes after 1.12.0 release

**Comment by DotBow** [comment]
Hi!

I know that this was long ago.. but maybe installing locales will fix the issue:
```
sudo dpkg-reconfigure locales
```

**Comment by Quijx** [comment]
So I have tried Blender Launcher again after quite some while and the issue seems to be gone. So I'm closing this for now.
