### ISSUE TITLE
"Create Symlink" feature not documented and doesn't work

### ISSUE THREAD

**Issue by benthillerkus** [DotBow/Blender-Launcher#28]
**Describe the bug**
Selecting the button in the menu seemingly does nothing, and it's [not documented in the wiki](https://github.com/DotBow/Blender-Launcher/wiki/Main-Window#build-context-menu).

**To Reproduce**
1. Download a build
2. Right click in in the library
3. Select "Create Symlink"
4. ?

**Expected behavior**
Honestly I don't know, I suppose that it creates a symlink in a fixed location?

**Screenshots**

**System (please complete the following information):**
 - Operation system: Windows 10 20H2
 - Blender Launcher version: v1.7.1

**Comment by DotBow** [comment]
Hi!
Thanks for pointing to missing information and sorry for outdated documentation.
I [added information](https://github.com/DotBow/Blender-Launcher/wiki/Main-Window#build-context-menu) about symbolik link.

**Comment by benthillerkus** [comment]
Where on my drive is the symlink being added? Should it be next to the daily / experimental / stable folders; directly in the library folder I've set in the settings?

I can't really find it 🤔

**Comment by DotBow** [comment]
> Where on my drive is the symlink being added? Should it be next to the daily / experimental / stable folders; directly in the library folder I've set in the settings?
> 
> I can't really find it 🤔

Well, I think it is pretty straight forward (except if something is broken):
Create symbolic link for selected build pointing to **%Library Folder%/blender_symlink**
Let me know if it is not working or explanation is unclear!
P.S. It is still kind of rough solution, maybe there should an option to select path manually, however the current restriction seems convenient.

**Comment by benthillerkus** [comment]
Oh right, I interpreted "pointing" as being the other way around. I think there might be a but then, because the symlink isn't being added for me

**Comment by DotBow** [comment]
> Oh right, I interpreted "pointing" as being the other way around. I think there might be a bug then, because the symlink isn't being added for me

Does it write any log info?
There was a bug in 1.7.0 but everything should be fine in 1.7.1

**Comment by DotBow** [comment]
Ok... that is interesting... Somehow there is a bug actually..

**Comment by DotBow** [comment]
Fixed in Blender Launcher 1.8.0 https://github.com/DotBow/Blender-Launcher/releases/tag/v1.8.0

**Comment by DotBow** [comment]
What happend again, after every release it somehow brokes! 🤒 
Reopening, will revisit later...

**Comment by DotBow** [comment]
@benthillerkus thanks very much for report and ptience! 
Figured out the problem (it worked in debug but not in build).

**Comment by benthillerkus** [comment]
Nice, it works now!

**Comment by ClemensBeute** [comment]
For anyone stumbling upon this. I had the problem that symlink didn't do anything.
But it wasn't the fault of blender launcher.
**As it turned out you cannot create symlinks on exFAT** (see https://askubuntu.com/questions/1322009/is-it-possible-to-create-symbolic-links-on-exfat-filesystem)

So I reformatted my drive to NTFS. Now it works :)

@DotBow But maybe you can add a hint, when someone is clicking on symlink and the drive has the wrong filesystem.
