### ISSUE TITLE
Add custom command line arguments

### ISSUE THREAD

**Issue by lucianomunoz** [DotBow/Blender-Launcher#29]
**Is your feature request related to a problem? Please describe.**
I want to be able to run blender with some string like a "--app- template 2D" or so whatever blender version i launch will start with that template 

**Describe the solution you'd like**
Adding an option in the preferences where you add the string that goes after the "exe" would be enough and so whatever you launch will pick that up (or could be only for the favourite build too)

**Describe alternatives you've considered**
I havent found alternatives as it is now i need to create a shortcut to each blender and add the string at the end, but given that im always moving into the newer bender versions this would lock me down because of the hassle.

**Comment by DotBow** [comment]
Hi! 
Thanks for suggestion!
Custom command line arguments feature will be available in 1.8.0 9ad1f36aa494197318b5ecd3bf7d50e9c43da469

**Comment by DotBow** [comment]
Added in Blender Launcher 1.8.0 https://github.com/DotBow/Blender-Launcher/releases/tag/v1.8.0
