### ISSUE TITLE
Omit launching multiple instances of Blender Launcher

### ISSUE THREAD

**Issue by LarsJandel** [DotBow/Blender-Launcher#3]
**Describe the bug**
Being too lazy to check, if _Blender Launcher_ is already running, I just click the app icon again to find a bunch of them in the tray already running later on. I like the option to run multiple instances of Blender itself, but I think there is no need to run multiple instances of the _Blender Launcher_. 😉

**To Reproduce**
1. Launch the app
2. Close = minimize the app
3. Launch the app again
4. Find a bunch of them in the tray

**Expected behavior**
Clicking the app icon e.g. in the start menu should bring the app in front if it is already running instead of launching another instance. Thanks.

**Screenshots**
![Program Manager 2020-05-26 11 42 32](https://user-images.githubusercontent.com/32457827/82886408-c59ab900-9f46-11ea-885d-74ae061fd478.png)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: v1.0.0

**Comment by DotBow** [comment]
Done in 30911359e2d2b4c6a5de39990ff1b8bdf02553aa
