### ISSUE TITLE
Launch using dedicated graphics card

### ISSUE THREAD

**Issue by Botoni** [DotBow/Blender-Launcher#30]
I'm using PopOs 20.10 on a hybrid laptop and if I launch Blender normally it tries to use the intel graphics and it crashes.

Blender needs to be launched with the command line "env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia /home/USER/Blender/stable/blender-2.91.0-linux64/blender"

My solution is to create a blender.desktop in /home/USER/.local/share/applications with the line "Exec=env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia /home/USER/Blender/stable/blender-2.91.0-linux64/blender %f" for each version of blender.

It would be nice if Blender Launcher would do that automatically or launch Blender using the nvidia card.

**Comment by DotBow** [comment]
Hi! 
Thanks for suggestion!
I think it can be solved with custom command line arguments.
Custom command line arguments feature will be available in 1.8.0 9ad1f36aa494197318b5ecd3bf7d50e9c43da469
Refer to #29

**Comment by DotBow** [comment]
Why the path to blender is at the end of command by the way?
> env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia /home/USER/Blender/stable/blender-2.91.0-linux64/blender

**Comment by DotBow** [comment]
By the way, does this part of command is the same for the most linux distributions?
> env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia

**Comment by Botoni** [comment]
I think it is, in vanilla ububtu and arch there's the comand prime, primus or prime-run or something like that, but I think it's jut an alias for the same arguments...

**Comment by DotBow** [comment]
> env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia nohup

Could you please check if adding **nohup** will work fine for you? 
It is necessary for redirecting output from main process.

**Comment by Botoni** [comment]
I added it to the "exec:" line of the .desktop file and blender still opens running on dgpu without problem.

**Comment by DotBow** [comment]
> I added it to the "exec:" line of the .desktop file and blender still opens running on dgpu without problem.

Thanks! 
Will add bash command option tomorrow.

**Comment by DotBow** [comment]
Added in Blender Launcher 1.8.0 https://github.com/DotBow/Blender-Launcher/releases/tag/v1.8.0
