### ISSUE TITLE
Add custom Template

### ISSUE THREAD

**Issue by Endertainer** [DotBow/Blender-Launcher#32]
There's one feature that I really wish were added to this launcher. Which is the ability to add custom Templates. This is because I use a custom template in my blender install. It contains a custom startup, preferences, and also custom splashes. I really wish there's a way to add these custom templates into a blender install in this launcher. I also want that you would install it in another version as well. Say that I just installed a new version of blender and I want that version to have and able to automatically start with that template. Usually for this, I install my template into the blender install and add `\blender.exe" --app-template your_template` into the shortcut.

**Comment by DotBow** [comment]
Hi! 
Thanks for suggestion!
Custom command line arguments feature will be available in 1.8.0 9ad1f36aa494197318b5ecd3bf7d50e9c43da469

**Comment by DotBow** [comment]
Merging with #29

**Comment by DotBow** [comment]
By the way:
> It contains a custom startup, preferences, and also custom splashes
> automatically start with that template. Usually for this, I install my template into the blender install
Could you please explain this part more? Will be nice to see folder structure as well (screenshots are welcome)!
P.S. Reopening because it seems I misunderstood part of issue 😅

**Comment by DotBow** [comment]
cc2a6a52b564b3b1a1a5dee89f161b92da94a435
7948ae9a0263a0648622f377cb01dc43523e7e15
7d81c8836285876de9ac7fbdef3455ea789fced1

**Comment by DotBow** [comment]
Added in Blender Launcher 1.8.0 https://github.com/DotBow/Blender-Launcher/releases/tag/v1.8.0
