### ISSUE TITLE
why cant i find my already downloaded blender builds?

### ISSUE THREAD

**Issue by Rhys-011003** [DotBow/Blender-Launcher#33]
![image](https://user-images.githubusercontent.com/55994011/100520805-d530de00-31c5-11eb-90d9-877a55fdb08c.png)

**Comment by DotBow** [comment]
Hi!
Could you please describe the issue better? 
What steps you've done, what happened and what you've expected?
If you trying to load custom builds, they should placed under %Library Folder%/custom folder. Make sure to restart Blender Launcher or press Reload Library Folder Contents in settings.
P.S. For upcoming 1.8.0 there will be a better solution for reloading custom builds.

**Comment by Rhys-011003** [comment]
![image](https://user-images.githubusercontent.com/55994011/100578510-74f68500-3308-11eb-8f68-ea33519433b7.png)

Thanks a lot i've got it to work

![image](https://user-images.githubusercontent.com/55994011/100578745-e46c7480-3308-11eb-87ff-56d0c08dba2e.png)

**Comment by DotBow** [comment]
Glad your problem solved!
