### ISSUE TITLE
can there be a way to delete builds without going thru windows explorer

### ISSUE THREAD

**Issue by Rhys-011003** [DotBow/Blender-Launcher#35]
![image](https://user-images.githubusercontent.com/55994011/100579476-509ba800-330a-11eb-9f76-37d5e986aaf7.png)

Maybe like this?

**Comment by DotBow** [comment]
Hi!
You can right click on build/multiple builds and in context menu choose "Delete From Drive".
![изображение](https://user-images.githubusercontent.com/32243930/100583886-65713f00-32fc-11eb-9548-88473e2d8ae8.png)
![изображение](https://user-images.githubusercontent.com/32243930/100583906-6b672000-32fc-11eb-8093-67adc2a67dfd.png)
