### ISSUE TITLE
Blender template won't work and Startup argument just crashes

### ISSUE THREAD

**Issue by Endertainer** [DotBow/Blender-Launcher#36]
So I've tried the new custom template feature in the new 1.8.0 update of Blender Launcher and it didn't work. Apparently, you put the custom template in the wrong place. It should be in `daily\blender-2.92.0-007a0e43a01a-windows64\2.92\scripts\startup\bl_app_templates_system` and you just put it on the blender main folder. Luckily, when I put the custom template in the right place, it works. So the way to fix this issue is to make sure that the custom template is put in the right place, which is `blender_main_folder\version\scripts\startup\bl_app_templates_system`. There's also an issue with the custom startup argument. To make my custom template start every time I open blender, I put `--app-template my_custom_template`. But when I tried to open blender, it just closes. It seems that it has to do with my custom template because I put it in the right folder (`daily\blender-2.92.0-007a0e43a01a-windows64\2.92\scripts\startup\bl_app_templates_system`) and when I modify the argument to just `--app-template`, it opens. I'm not really sure what happened because it went too quickly, but I hope this issue could be fixed and I can automatically start my own custom template. But it's still a nice update and I really like it. Keep up the good work and good luck.

**Comment by DotBow** [comment]
Hi!

1. The "template" feature is not the the same as "bl_app_templates_system" you are talking about. 
It meant to solver general problem of migrating custom configurations.
As explained in [here](https://github.com/DotBow/Blender-Launcher/wiki/Library-Folder#template), you should use the full path to to specific folders (root is what you called "version" folder):

`%Library Folder%/template/scripts/startup/bl_app_templates_system`

2. Yeah, that's a bug with multiple args, fixing...

**Comment by DotBow** [comment]
Fixed in 3084a49
