### ISSUE TITLE
Empty blender app file

### ISSUE THREAD

**Issue by j2l** [DotBow/Blender-Launcher#38]
**Describe the bug**
After successfully running Blender Launcher and restarted the PC, /media/pm/Data/000blender/Blenders/stable/blender-2.91.0-linux64/blender file is now 0 byte. All the rest is here but Blender was emptied.

**To Reproduce**
No idea what went wrong

**Expected behavior**
Launch Blender

**System (please complete the following information):**
 - Operation system: Ubuntu (PopOS) 20.04
 - Blender Launcher version: 1.8.0

**Additional context**
I updated Blender Launcher before restarting the PC. Not sure if it's related.

Thanks for your great app. 
Can't wait to be able to share Blender add-ons between versions, with symlinks or else.

**Comment by DotBow** [comment]
Hi!
Thanks for report!
Information is poor on what actually happened, especially that you restarted PC...
If it will happen again, please, let me know, I'll leave it for now.
