### ISSUE TITLE
Only 1.5 version works in my Windows

### ISSUE THREAD

**Issue by xcarlossilva** [DotBow/Blender-Launcher#39]
Hello, 
My name is Carlos and I donwload all verisions but only 1.5 version works in my computer.

64 bits
Windows 10 Home Single Language
version: 1909
Compilation of OS 18363.1198

I tested all the versions of bleder launcher with another windows target 8,10 versions, like administrator but not happens. The program not start.

**Comment by DotBow** [comment]
Hi! Thanks for report! Sorry fro having such annoying issue.
In 1.6.0 the new PyInstaller 4.0 was introduced for building releases. That might be an issue here.
I will try to build with 4.1 which was released recently and give you to test it.

**Comment by DotBow** [comment]
Try this one please:
https://drive.google.com/file/d/1T4FUM9ONSZGpoX905Hz6wz4i0ZcD-3LB/view?usp=sharing
Maybe it will solve the issue since the only peg to hung on is updated version of PyInstaller after 1.5.0

**Comment by xcarlossilva** [comment]
Hello,
This build version works!!! 
![image](https://user-images.githubusercontent.com/33121567/100996718-c765ba80-352f-11eb-984a-3a27a9f37ea8.png)

**Comment by DotBow** [comment]
Hi!
Please, [manually update](https://github.com/DotBow/Blender-Launcher/wiki/Installation#updating-blender-launcher) to release version of 1.9.0 https://github.com/DotBow/Blender-Launcher/releases/tag/v1.9.0
