### ISSUE TITLE
.temp folder: zip files remain after the installaton has finished

### ISSUE THREAD

**Issue by LarsJandel** [DotBow/Blender-Launcher#4]
**Describe the bug**
_Blender Launcher_ creates and uses a `.temp` folder to download the zips into. The zips just keep on stacking up, filling up disc space. I have to delete them manually. Yeah, being lazy again, sorry.

**To Reproduce**
1. Use the app for multiple downloads/installations
2. Have a look inside the .temp folder
3. Find all the zips

**Expected behavior**
I would expect the zips to get deleted automatically, or have an option for this behaviour.

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: v1.0.0

**Additional context**
Thanks.

**Comment by DotBow** [comment]
Done 8150dfb4b8421280be31ec09604ff71363d0518d
