### ISSUE TITLE
Existing Files not Recognized

### ISSUE THREAD

**Issue by TakingFire** [DotBow/Blender-Launcher#42]
**Describe the bug**
I have just uninstalled Blender Project Manager after noticing this new version.
However, on opening the application and setting the path to Documents, which is where my installs lie, neither official folders nor Project Manager's git files are recognized. I am not seeing this in any closed issues, which is is certainly strange.

**To Reproduce**
1. Open BL 1.9.0
2. Follow opening prompts to set path
3. Wait for check to finish with no results.

**Screenshots**
![Screenshot 2020-12-13 151434](https://user-images.githubusercontent.com/38340654/102027207-6459fc00-3d57-11eb-9107-eba0bfe49181.png)

**System (please complete the following information):**
 - Operation system: Windows 10 20211
 - Blender Launcher version: 1.9.0
 - Log file: No output.

**Comment by DotBow** [comment]
Hi!
This is an intended behavior.
Referring to this [note for Blender Version Manager Users](https://github.com/DotBow/Blender-Launcher/wiki/Installation#blender-version-manager-users) you should put builds inside %Library Folder%/daily folder and restart BL.
Or, if you want to use custom builds, then put it inside %Library Folder%/custom folder and press "Reload" button on left top corner of "Custom Builds" tab.
