### ISSUE TITLE
Wacatac.B!ml Troyan when i update Blender-Launcher!

### ISSUE THREAD

**Issue by TebitoSan** [DotBow/Blender-Launcher#43]
**Describe the bug**
windows alert for Wacatac.B!ml Troyan

**To Reproduce**
1. Go to 'Update'
2. Click on 'Update'

**Screenshots**
https://images-ext-1.discordapp.net/external/Fgb0ncuhAeyv4PVABD0Zo6NDc5VOrCLfL3WBH6PusV8/https/i.gyazo.com/cd5b74a60a7ad55cd2ae78f3dde52266.png

**System (please complete the following information):**
 - Operation system: [Windows 10]

**Comment by DotBow** [comment]
Hi!
This is probably false positive.
I check updating myself after every release, so everything is fine on my side.

**Comment by DotBow** [comment]
I downloaded and checked files myself:

![изображение](https://user-images.githubusercontent.com/32243930/102234209-1e8d6700-3f02-11eb-8080-8382a62c655e.png)

**Comment by jlampel** [comment]
I get the same thing with Windows Defender, which is default in Windows 10 and it blocks then deletes the .exe if you try to run it. 
![image](https://user-images.githubusercontent.com/12982300/102252736-4b6a5b80-3ebb-11eb-932d-1364dbb246b7.png)

**Comment by DotBow** [comment]
> 
> 
> I get the same thing with Windows Defender, which is default in Windows 10. It blocks then deletes the .exe if you try to run it.
> ![image](https://user-images.githubusercontent.com/12982300/102252736-4b6a5b80-3ebb-11eb-932d-1364dbb246b7.png)

That's weird...
I downloaded file an hour ago and no any warnings were shown.
But when I downloading it now it shows the trojan 🤔

**Comment by andyeff** [comment]
The information for Wacatac.B!ml seems a bit limited, but virustotal.com also has two engines recognise it as 'Scar'

F-Secure has a bit more detail which might be useful in finding out why the Blender Launcher gets tagged as malware:

> Trojan:W32/Scar downloads a text file containing URLs that link to other malicious executables.

> When executed, Scar downloads the executables listed in the text file from remote servers. The downloaded files are then silently executed in the background. The executables can be trojan-downloaders, trojan-PSWs, keyloggers or monitoring tools, email worms or bots, and so on. Each may have its own payload.

From this, I can only guess that the Blender Launcher runs in a similar-enough way to actual malware, that it also unfortunately gets classed as malware itself. I'm afraid I'm not good enough at coding myself to recommend some kind of fix for this.

**Comment by DotBow** [comment]
Even Virus Total doesn't show Wacatac.B!ml, just some false positive generic stuff.
![изображение](https://user-images.githubusercontent.com/32243930/102255513-3e7d5480-3f1b-11eb-9288-6d732cdb08cb.png)
I think it somehow related to Windows malware database so it think there is something when it is not.

**Comment by andyeff** [comment]
Oh my apologies, I ran virustotal against a previous version which I tried to use the auto update behaviour (1.7.1 I think)

The newest version shows up as per your screenshot just now, Dotbow:  
https://www.virustotal.com/gui/file/94d934847e8b926eef61f8fd8dc9fcfa00fd6493d1ce79dcc361e24531dbbdb8/detection

**Comment by DotBow** [comment]
> 
> 
> The information for Wacatac.B!ml seems a bit limited, but virustotal.com also has two engines recognise it as 'Scar'
> 
> F-Secure has a bit more detail which might be useful in finding out why the Blender Launcher gets tagged as malware:
> 
> > Trojan:W32/Scar downloads a text file containing URLs that link to other malicious executables.
> 
> > When executed, Scar downloads the executables listed in the text file from remote servers. The downloaded files are then silently executed in the background. The executables can be trojan-downloaders, trojan-PSWs, keyloggers or monitoring tools, email worms or bots, and so on. Each may have its own payload.
> 
> From this, I can only guess that the Blender Launcher runs in a similar-enough way to actual malware, that it also unfortunately gets classed as malware itself. I'm afraid I'm not good enough at coding myself to recommend some kind of fix for this.

Why this is a thing after couple of days, not right after the release? 
As I said, couple hours ago everything was fine.

**Comment by DotBow** [comment]
It also says that  Wacatac.B!ml runs "Wacatac" process, however there is no such thing at all.
Google says some cracks and other similar "pirate" software also detects as this virus 😂

**Comment by aditiapratama** [comment]
![image](https://user-images.githubusercontent.com/982553/102295104-a4062b00-3f85-11eb-903d-10395cde237e.png)
just trying update feature and notice this as well

**Comment by DotBow** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/982553/102295104-a4062b00-3f85-11eb-903d-10395cde237e.png)
> 
> I tried both way, downloading from release page and update from apps will give this report

Because updater uses the same file from github. 
It 100% false positive - no other antiviruses shows this issue.
Also, windows defender simply does nothing when trying to delete "virus".
I think it related to updated PyInstaller 4.1 and the way it packs exe.
Anyway, before tomorrow everything was just fine - I checked updater and zip archive by myself without in day of 1.9.0 release.

**Comment by DotBow** [comment]
There is issues on PyInstaller page talking that it also because someone uses it for making actual viruses/cracks so other apps starting to recognized as malware 😞 
https://github.com/pyinstaller/pyinstaller/issues/4633

**Comment by MarkBTomlinson** [comment]
Had the same issue after working fine this morning Windows decided to delete the launcher.exe without warning or asking. 
I guess better to be annoying and wrong than miss something and regret it. 
So python installer is getting flagged by Windows, interesting to know.
Good luck!

**Comment by DotBow** [comment]
> Had the same issue after working fine this morning Windows decided to delete the launcher.exe without warning or asking.
> I guess better to be annoying and wrong than miss something and regret it.
> So python installer is getting flagged by Windows, interesting to know.
> Good luck!

This is something that I can't affect because there is handreds of different modules involved in building exe. 
And there is thousands of patterns that can be classified as virus.

**Comment by DotBow** [comment]
I submitted file to Microsoft Security Intelligence service as incorrect detection, will see if it have any impact on situation.

**Comment by DotBow** [comment]
Good news!
They removed detection! 
Don't know how exactly this work, as far as I understand it will be in the next update of Windows Defender:

![изображение](https://user-images.githubusercontent.com/32243930/102377622-f2dbb100-3fd5-11eb-9ea6-d9d4d8da4106.png)

**Comment by MarkBTomlinson** [comment]
Wow! That was quick well done.

**Comment by jlampel** [comment]
I followed the instructions in that screenshot and I can now use it again. Thank you!

**Comment by MarkBTomlinson** [comment]
OCR of the image to save typing;

Submission details:

blender launcher.exe
Submission 'D: 7df9bc43-c772-437a-8b63-1ed64df907eb
Status: Completed
Submitted by. valveoleg@gmail.com
Submitted: Dec 16, 2020
user Opinion: Incorrect detection

Analyst comments:
We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run MpCmdRun.exe -removedefinitions -dynamicsignatures
3. Run MpCmdRun.exe -SignatureUpdate

Alternatively, the latest definition is available for download here: https://w.vw.microsoft.com/en-us/wdsi/definitions
Thank you for contacting Microsoft.
Click here for more information
