### ISSUE TITLE
Download link for 1.9 delivers 1.8.1

### ISSUE THREAD

**Issue by micr0n0va** [DotBow/Blender-Launcher#44]
Downloading the Blender_Launcher_v1.9.0_Windows_x64.zip delivers the 1.8.1 version instead of 1.9.

**To Reproduce**
Download from the github 'latest version' link.

**Expected behavior**
v1.9

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: This is a very good question.

**Comment by DotBow** [comment]
Hi!
I can't confirm that file is wrong in zip archive.
You probably not closed running version (1.8.1) of BL.

**Comment by micr0n0va** [comment]
You are correct! Sorry for the trouble.

**Comment by DotBow** [comment]
> You are correct! Sorry for the trouble.

That's ok!
I actually will keep this isdlsue open as a reminder.
I should make a proper check on startup:
- If running version is higher or lower it will warn the user
- If versions the same then simply open the running one

**Comment by 48design** [comment]
Hi!
I thought the same (wrong zip delivered) but for me it seems the problem is that Windows deletes the newly installed version caused by a virus/trojan warning since 1.9, which leads to Blender Launcher starting 1.8.x again.

**Comment by DotBow** [comment]
> Hi!
> I thought the same (wrong zip delivered) but for me it seems the problem is that Windows deletes the newly installed version caused by a virus/trojan warning since 1.9, which leads to Blender Launcher starting 1.8.x again.

Hi!
The issue with incorrect detection already solved in #43
