### ISSUE TITLE
Option to not use tray/quick on dialog close

### ISSUE THREAD

**Issue by willgfx** [DotBow/Blender-Launcher#45]
I personally don't like to leave applications running in the background all the time and prefer to close them when not in use.

I would like for Blender Launcher to have an option that controls whether it minimizes to the tray upon closing the main dialog.

Most apps call this setting "minimize to tray on close", so the current behavior would be how it is when enabled. When disabled, the application will quit when the main dialog is closed rather than having to use the tray icon to quit.

**Comment by DotBow** [comment]
Hi! 
I can get your point, but BL uses approximately only 40 mb of memory and tray gives you quick access to favorite build.
Anyway, thanks for feedback, will schedule this for next release!

**Comment by willgfx** [comment]
Thanks!

I use the shortcuts created by BL to launch Blender, like I would with any other application.

**Comment by DotBow** [comment]
Implemented in 1.10.0 https://github.com/DotBow/Blender-Launcher/releases/v1.10.0
