### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by Iglum** [DotBow/Blender-Launcher#47]
Have you thought about activating GitHub Discussions?

[GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions)

**Comment by DotBow** [comment]
Hi! 
It is getting a bit out of control - too many attention to a project.
I'm putting more time to BL than I expected, especially taking in consideration that it is free and I don't want it to be something commercial.
Anyway, thanks for suggestion!
I will check it later and see if it really needed.

**Comment by DotBow** [comment]
It seems this feature is still in beta for a range of chosen repos. Can't find way to activate it.
