### ISSUE TITLE
Not shutting down properly

### ISSUE THREAD

**Issue by 0z3l07** [DotBow/Blender-Launcher#50]
**Describe the bug**
When you close out BL with the tray icon while having the app running in the foreground it will still remain active but in a not responding state. So its not properly shutting down.

**To Reproduce**
- open BL so that it is visible on screen
- go to bottom right tray icon and right click "quit"
![Screenshot 2021-01-23 132521](https://user-images.githubusercontent.com/24977832/105578160-754a5400-5d7e-11eb-9aae-fc1026856d07.png)
- try icon disappears but the window will remain open
- once you click on it it will turn grey and gives you the "not responding, close/wait" msg
![Screenshot 2021-01-23 132412](https://user-images.githubusercontent.com/24977832/105578124-4d5af080-5d7e-11eb-9dd8-1d022533627f.png)

**System (please complete the following information):**
 - Operation system: win 10
 - Blender Launcher version: 1.9
 - Log file: no log

Seems to be also the case if its not open in a visible state...not closing down from task manager(2 BL.exe even tho the tray icon is gone aka it should be closed)

**Comment by DotBow** [comment]
Hi! Thanks for feedback!
Fixed in 1.9.1 https://github.com/DotBow/Blender-Launcher/releases/tag/v1.9.1
