### ISSUE TITLE
I need to know how to cleanly remove the launcher record (setting value) from the system

### ISSUE THREAD

**Issue by issacmaya** [DotBow/Blender-Launcher#55]
I want to record the teaching, but because I have used Blender Launcher, I can't see the scene like choosing the path at the beginning.
I think I need to know how to cleanly remove the launcher record (setting value) from the system

**Comment by DotBow** [comment]
Hi!
Since I answered it on [Blender Artsits](https://blenderartists.org/t/blender-launcher-standalone-software-client/1230543/108?u=dotbow), I can close it here.
