### ISSUE TITLE
Version Column size doesnt adjust for certain lenght

### ISSUE THREAD

**Issue by 0z3l07** [DotBow/Blender-Launcher#56]
**Describe the bug**
The version column is not adjusting itself to display certain words like release or alpha
This seems to be in the daily tab

**Screenshots**
![Screenshot 2021-02-25 210102](https://user-images.githubusercontent.com/24977832/109210074-a0282d80-77ac-11eb-969d-e421e648f4aa.png)
![Screenshot 2021-02-25 210117](https://user-images.githubusercontent.com/24977832/109210077-a1595a80-77ac-11eb-8519-bb226f1a9ff1.png)

1.10 on win 10

**Comment by DotBow** [comment]
Hi! 
Thanks for report!
It is already fixed in the upcoming release.

**Comment by DotBow** [comment]
Fixed in 1.11.0
https://github.com/DotBow/Blender-Launcher/releases/tag/v1.11.0
