### ISSUE TITLE
Status: Connection Error

### ISSUE THREAD

**Issue by M0WW0M** [DotBow/Blender-Launcher#6]
After working perfecly the Blender Launcher is giving me only Status:Connection Error. No bl.log file

Running win 10 with a stble and working internet Connection

**Comment by DotBow** [comment]
Hi!
Fixed in 1.1.0 8faba262d9da268a86a6e2d7970bfe0741eb4d19

**Comment by M0WW0M** [comment]
Thanks! That was quick :D
