### ISSUE TITLE
Custom library for 3rd party blender builds

### ISSUE THREAD

**Issue by 0z3l07** [DotBow/Blender-Launcher#60]
I would like to propose a custom path where BL would pick up a defined blender.exe and you can put it into your library and give it a custom name. 

That would be useful for like e-cycles/octane/blender for artists builds for example so you have a centralized space in BL where you can start them(its not about the update process since they only offer packed releases for manual download). 
This is more of a OCD request to not have multiple shortcuts on your desktop or taskbar and reduce clutter. 

Thx for considering :)

**Comment by DotBow** [comment]
Hi!

It is already possible to use custom builds. You should put them inside `custom` folder and they will appear under User->Custom page after pressing reload button.
Here is more information on topic:
https://dotbow.github.io/Blender-Launcher/library_folder/#custom
https://dotbow.github.io/Blender-Launcher/user_interface/#custom-page

**Comment by 0z3l07** [comment]
Oh sry my bad
