### ISSUE TITLE
Is there a mac version in the pipeline?

### ISSUE THREAD

**Issue by theCreativeMind-mrTP** [DotBow/Blender-Launcher#61]
Hi Oleg,

is there a chance to see a mac version of your blender launcher in the near future?

thx

**Comment by DotBow** [comment]
Hi!
Well, the obvious problem with Mac is that you either need to have one or install it on virtual machine. Sadly both of this is not very trivial 😞 Maybe I will have time to look at it again and find solution.

Merging issue to #22, feel free to continue discussion there.
