### ISSUE TITLE
Subversion label doesn't fit five-digit version numbers

### ISSUE THREAD

**Issue by 0z3l07** [DotBow/Blender-Launcher#62]
Seems like that some lts number length will cause certain letters to be cut off

Daily tab downloads

![Screenshot 2021-04-22 113431](https://user-images.githubusercontent.com/24977832/115692069-ee961a80-a35e-11eb-8b48-747c3b9a7fdd.png)

**Comment by DotBow** [comment]
Hi! Thanks for report.
Yes, I saw this one... Slowly working on next release so cross fingers for next release...
