### ISSUE TITLE
Blender Launcher is not founding new experimental builds. (cycles-x)

### ISSUE THREAD

**Issue by gadaszewski** [DotBow/Blender-Launcher#66]
**Describe the bug**
Hello, I think the https://builder.blender.org/* was updated, because the Blender Launcher can't get links for new experimental branches.

**To Reproduce**
1. Start Blender Launcher
2. Look for Experimental > Downloads
3. We can't find any cycles-x build.

**Screenshots**
![chrome_Hy8WIPjNeK](https://user-images.githubusercontent.com/32915902/118824664-5423eb00-b8ba-11eb-9abe-2245f0784092.png)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.12.0
 - Log file: 
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/6509251/Blender.Launcher.log)

**Additional context**
Imo, the Blender website has changed layout, and something is not correctly getting URL's for builds. :)

**Comment by DotBow** [comment]
Hi!
Yep, its known issue since yesterday caused by massive site update including archives naming.
Merging to #65
