### ISSUE TITLE
Failed to update and display each build twice 

### ISSUE THREAD

**Issue by AdrienGomez** [DotBow/Blender-Launcher#67]
**Describe the bug**
Whan Clicking Update to Version 1.12.1, a pop up Updating Blender Launcher is opening and extracting stay at 0%. Also each Build is displayed twice. Those issues appears on both my computer, desk and laptop

**To Reproduce**
1.Open Blender Launcher
2. Click on Update to Version 1.12.1'
3. See error

**Expected behavior**
Update to new version. Dispay each build only once

**Screenshots**

![Capture d’écran 2021-05-20 104927](https://user-images.githubusercontent.com/57804480/118949092-30fc4880-b959-11eb-89f2-7d6752c0c223.jpg)

**System (please complete the following information):**
 - Operation system: Windows 10 64 bit
 - Blender Launcher version:  1.12.0
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Comment by DotBow** [comment]
Hi! Thanks for report!

Yes, it's known issue. You should download new version manually.

**Comment by DotBow** [comment]
Ok, the updater is fixed now, it was late night and I messed up the tags 😑

**Comment by AdrienGomez** [comment]
Ok sorry for reporting a know issue. I download the new version. Everything work fine. By the way, thank you very much, Blender launcher is awsome!!!
