### ISSUE TITLE
Feature request: Batch script execution after unpacking

### ISSUE THREAD

**Issue by Ulf3000** [DotBow/Blender-Launcher#69]
**Is your feature request related to a problem? Please describe.**

Im using a specific ocio config + the related spi3d file to get the best colors.

Right now i have to copy the 2 files over every time i download a new blender version.

**Describe the solution you'd like**

it would be nice if i could auto-copy the files into the new folder after installing. 

maybe something like triggering a batch script which has the new folder as an argument/var

Other people might use this for other files. (like replacing the pythonfolder with a symlink or whatever you can think of basically)

**Comment by DotBow** [comment]
Hi!

Sorry for late answer. Maybe you can use a template feature? It does exactly what you want - copies files inside blender build folder.

**Comment by Ulf3000** [comment]
ohh man didnt realize it , thanx so much ! worked perfectly !
