### ISSUE TITLE
Manually invoke checking for new builds

### ISSUE THREAD

**Issue by LarsJandel** [DotBow/Blender-Launcher#7]
**Is your feature request related to a problem? Please describe.**
Currently I have to quit BL and launch the app again in order to have BL check for new builds. Feels a bit like a bug, too..? 😉

**Describe the solution you'd like**
I think, this deserves a dedicated button. As the check takes a few seconds, I guess having this happen automatically when bringing BL to the front, won't be ideal. With a button, the user can decide when to check again. Maybe only visible, when the user is on the _Downloads_ tab?

**Describe alternatives you've considered**
RMB on the _Status_ at the bottom of BL to open a context menu would be another option - just a bit hidden.

Thanks.

**Comment by LarsJandel** [comment]
...or does BL already check every x minutes. Should watch the time in the _Status_...

**Comment by LarsJandel** [comment]
Okay, it does: Every 10 minutes.
So I guess, a button isn't really needed. Maybe a RMB context menu for the inpatient users. 😂
You can close this otherwise.
...I should be more patient and test / explore more before posting. Sorry. 🤷‍♂️

**Comment by DotBow** [comment]
It is a bit out of scope - as a user you shouldn't think about updating. Also, builds get updated only couple of times per day on blender.org. I would like to add notifications for new builds, that is more important feature.

**Comment by LarsJandel** [comment]
Notifications sound great - thanks!

**Comment by DotBow** [comment]
Closing this because it isn't really an issue or proposal... Thanks for attention anyway!
Also, now there is an ability to force reload library and downloads from settings (although it needs more polishing).
