### ISSUE TITLE
2.93 LTS is displayed as windows64 as Version

### ISSUE THREAD

**Issue by 0z3l07** [DotBow/Blender-Launcher#70]
Simple and youre prob already aware of it
![Screenshot 2021-06-02 205554](https://user-images.githubusercontent.com/24977832/120536913-f11b7380-c3e4-11eb-812a-f3c97839421b.png)
The download is also still possible even tho you already got 2.93 in your library. Prob because of the naming issue
Release notes also dont work

**Comment by pozproductions** [comment]
Also experimental builds shows "Windows64" as branch once downloaded
![image](https://user-images.githubusercontent.com/71019630/120610041-1050ea00-c453-11eb-91c3-b981ae3e3cdc.png)
the naming issue is non only in blender launcher interface but also in the directory structure:
![image](https://user-images.githubusercontent.com/71019630/120610475-7e95ac80-c453-11eb-8ea2-24d215a2bc30.png)

**Comment by ValentinN84** [comment]
It seems to be the new naming convention for Windows. The 2.93.1 RC1 uses the same directory name, there's no more version in the name, 
The major issue is you cannot have multiple instances of the same version installed as Blender Launcher will always overwrite the directory with the newest version you install. It always screwed my template setup (I update daily in Alpha/Beta), good thing I always update the Template from the previous install before installing a new instance.

**Comment by ValentinN84** [comment]
Another issue is that in my case the 2.93 Stable gets filtered to the Daily tab instead of Stable.
Initially I thought it was because the directory nomenclature changed before the stable version was release, sometime in the beta stage. But now I've tried removing all local 2.93 entries on my PC and installing just the stable but it still gets put on the Daily tab of the Library.

**Comment by TitusLVR** [comment]
+1 Same issues

**Comment by DotBow** [comment]
Hi!
I know that issue exists, sorry.
Right now I have a bit of a hard time in my life and can't work on BL as before.
I will try to fix it asap. The 1.13 already have most of issues fixed.

**Comment by DotBow** [comment]
Note for myself: 
merged fix from @osamaar #73, though info reading for experimental builds will fail because there is no longer branch name in folder.
