### ISSUE TITLE
Blender 2.93.0 LTS does not get labelled corrrectly

### ISSUE THREAD

**Issue by HomoMilk** [DotBow/Blender-Launcher#72]
When downloading Blender 2.93.0. with the launcher, the version gets named "windows64" in both the launcher and the folder structure.

**To Reproduce**
Download Blender 2.93.0.
Done

**Expected behavior**
Show version 2.93.0. as with all the other versions. None of the other blender versions downloaded with blender launcher have this issue

**Screenshots**
![image](https://user-images.githubusercontent.com/85444987/120926954-62a63b00-c6df-11eb-86dd-cb6b3e3914fd.png)

**System (please complete the following information):**
 - Operation system:  Windows 10
 - Blender Launcher version: 1.12.0
 - Log file[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/6604295/Blender.Launcher.log)

**Comment by andyeff** [comment]
I also ran into this problem getting the latest Cycles X build from the experimental list - it also is listed as 'Windows64' as the branch

![image](https://user-images.githubusercontent.com/3918580/121089476-1d693280-c7df-11eb-90be-701cd91fd449.png)

**Comment by DotBow** [comment]
Duplicate, merging to #70
