### ISSUE TITLE
Shortcut key to switch to last used tool.

### ISSUE THREAD

**Issue by AtulD7** [DotBow/Blender-Launcher#77]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AtulD7** [comment]
I have to keep selecting the tool over and over while I am modeling stuff in Blender. I recently switched from cinema 4d to blender and I  love the feature of being able to switch to the last used tool in cinema 4d and would love to have it in Blender as well.

**Comment by DotBow** [comment]
Hi!
This is not an official Blender repository. If you want to propose a feature for Blender use https://blender.community/c/rightclickselect
