### ISSUE TITLE
Stuck on some background task after startup, unable to download new Blender versions.

### ISSUE THREAD

**Issue by ogierm** [DotBow/Blender-Launcher#8]
**Describe the bug**
When I start the software it seems to be stuck on some indexing task or so. I can go into the settings and the UI is responsive - it's just not doing anything in the background. I've wiped the directory that I set as the install directory.

**To Reproduce**
1. Go to start the program

**Expected behavior**
That the program showed no installed Blender versions and let me install new ones.

**Screenshots**
![image](https://user-images.githubusercontent.com/29630575/83543409-9fec5180-a4fc-11ea-9e4c-9ef498b26039.png)

**System (please complete the following information):**
 - Windows 10 1906 x64
 - Blender Launcher version: v1.1.0
 - Log file: [BL.log](https://github.com/DotBow/Blender-Launcher/files/4718376/BL.log)

**Additional context**
Just tried this out for the first time, so no clue if this had worked earlier.

**Comment by DotBow** [comment]
Hi!
You are using UAC protected (need admin rights) folder for library, change it to non system disk or at least create one in documents.

**Comment by ogierm** [comment]
Sure? Because this folder worked with Blender Version Manager. I think the C drive is safe aslong as you aren't in a folder like Programs

**Comment by DotBow** [comment]
You might be right, it seems you set some blender installation as Library Folder then. So, change it anyway.

**Comment by ogierm** [comment]
_wtf_
Was about to set this to a different folder, but upon opening Blender Launcher it already worked. I guess just restarting the PC was needed.

> it seems you set some blender installation as Library Folder then
No I just named that folder _Blender Foundation_ for consistency. It was my _Blender Version Manager_ library beforehand and there it worked just fine.

**Comment by DotBow** [comment]
Glad to hear everything work! Still weird that something broke.
