### ISSUE TITLE
Blender Launcher wont run on win 10

### ISSUE THREAD

**Issue by aabdelrehim** [DotBow/Blender-Launcher#80]
**Describe the bug**
Blender Launcher won't run any blender version or even update on windows 10. I looked into all the issues with no solution. I have it working on a different PC but on my personal laptop, it just doesn't. Blender works fine too.

Downloads fine too

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.13.0
 - Log file: no log file produced.

**Comment by DotBow** [comment]
Hi! Sorry for late answer.
Are you running BL from system (C:) drive? Or library folder is on system (C:) drive?

**Comment by aabdelrehim** [comment]
> Hi! Sorry for late answer.
> Are you running BL from system (C:) drive? Or library folder is on system (C:) drive?

sorry for the late reply, no.. a completely different drive. blender immediately closes after launching through the program.

**Comment by DotBow** [comment]
Sorry for late response. It might be possible that issue related to blender configuration or addon.
