### ISSUE TITLE
stuck in downlead and progress bar

### ISSUE THREAD

**Issue by Artistkw3d** [DotBow/Blender-Launcher#85]
System (please complete the following information):
 - Operation system: [Windows 10-64bit]
 - Blender Launcher version: [v1.13.0]
 - Log file: [included]

hi, recently blender has an update for LTS Version 2.93.2

and Mine is 2.93.1

include a screenshot and log file in google drive.

https://drive.google.com/drive/folders/18XggOLAc85EUQ5Jic27ZsqQIKzFndJPe?usp=sharing

**Comment by DotBow** [comment]
Hi!
 - Try to change you Library Folder to non system folder, preferably non system drive.
 - Clear the .temp folder and try to download again

**Comment by Artistkw3d** [comment]
it works when I change the library to (C:/Blender Launcher) create the folder manually
