### ISSUE TITLE
On Linux scraper not filtering *.sha256 files

### ISSUE THREAD

**Issue by cg-Kdaf** [DotBow/Blender-Launcher#89]
**Describe the bug**
The downloading of experimental builds of long named branches, is stuck. It downloads the .sha256 file, but no more. See the pic : 
![Screenshot_20210821_120859](https://user-images.githubusercontent.com/37415747/130318482-a00995cc-f932-44ce-a261-c0c9c8df6e84.png)

**System :**
 - Operation system: Linux 5.11.0-25-generic # 27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Blender Launcher version: 1.13 - 1.14 both not working
 - Log file: nothing in it

**Comment by DotBow** [comment]
You can load the dev build with fix from here:
https://drive.google.com/file/d/1_QXTGdNGtNmykJoM1JvJ-0UDw8Yvcty5/view?usp=sharing

**Comment by cg-Kdaf** [comment]
Yes, working fine now, thanks ;)

**Comment by DotBow** [comment]
Fixed in 1.14.0
@cg-Kdaf please, download stable version manually since dev build will not update automatically.
