### ISSUE TITLE
How do I execute it on Windows?

### ISSUE THREAD

**Issue by NazzarenoGiannelli** [DotBow/Blender-Launcher#9]
I know, dumb question, but I do not understand how to actually run it on Windows 10.
Thanks

**Comment by FinnT730** [comment]
When you first start up the program, you need to select an folder where you wanna store all of the builder downloads.
Then, when you launch it, you need to go to the downloads tab, and select an version you want.

**Comment by NazzarenoGiannelli** [comment]
Unfortunately, I do not understand which of the provided files starts up the program 😅

**Comment by FinnT730** [comment]
Am I able to assume you are doing it from the source? And are not using one of the releases? ❓

**Comment by NazzarenoGiannelli** [comment]
🤦‍♂️
I knew I was missing some really simple stuff.
Just to be foolproof, it would be nice to have a link to releases also in the README.md page.

Anyway...all good now in here :)
Really nice launcher!

**Comment by DotBow** [comment]
@NazzarenoGiannelli thanks for feedback! I will improve main page!
@FinnT730 Thanks for helping out!
