### ISSUE TITLE
Self update fails

### ISSUE THREAD

**Issue by brunnerh** [DotBow/Blender-Launcher#91]
**Describe the bug**
Tried to update from 1.12.1 to 1.13.0 via the update button in the application.

It showed this dialog for a split second and nothing else happened:
![image](https://user-images.githubusercontent.com/834235/130364353-fcc167e9-475d-4730-9dc8-30c12fcba9eb.png)

It did not log errors.

**To Reproduce**
1. Start launcher
2. Click update button

I doubt that this will reproduce everywhere, but it is consistent for me.

**Expected behavior**
Launcher updates.

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: v1.12.1

**Comment by DotBow** [comment]
Hi! Thanks for feedback and sorry for late answer.
Where do you placed BL exe file? 
For the time being you can update it manually.

**Comment by brunnerh** [comment]
The path would this, if that is what you are asking:

> D:\blender-launcher\Blender Launcher.exe

The drive is exFAT formatted, in case that could matter.

**Comment by brunnerh** [comment]
I assume that the launcher copies itself to update the main executable. It manages to do as much and the copy is started with the update command line argument, but the update itself seems to fail.

Updated manually now. Thank you for this great software by the way; it makes getting and managing daily builds so much easier.

**Comment by DotBow** [comment]
> I assume that the launcher copies itself to update the main executable. It manages to do as much and the copy is started with the update command line argument, but the update itself seems to fail.
> 
> Updated manually now. Thank you for this great software by the way; it makes getting and managing daily builds so much easier.

Thanks!
Could you confirm that 1.13.0 updated successfully to 1.14.0?

**Comment by brunnerh** [comment]
It launched this:

```shell
"Blender Launcher Updater.exe"  -update v1.14.0
```

But even after 25min nothing happened; the main thread is just doing the QT event loop:

```
win32u.dll!NtUserMsgWaitForMultipleObjectsEx+0x14
USER32.dll!MsgWaitForMultipleObjectsEx+0x9e
Qt5Core.dll!QEventDispatcherWin32::processEvents+0x622
qwindows.dll!qt_plugin_query_metadata+0x1f99
Qt5Core.dll!QEventLoop::exec+0x1bc
Qt5Core.dll!QCoreApplication::exec+0x154
QtWidgets.pyd!PyInit_QtWidgets+0x927c7
python39.dll!PyDict_MergeFromSeq2+0xbd9
python39.dll!PyEval_EvalFrameDefault+0x3f0f
python39.dll!PyEval_EvalFrameDefault+0x1ff5
python39.dll!PyObject_GC_Del+0xf53
python39.dll!PyEval_EvalCodeWithName+0xa9
python39.dll!PyEval_EvalCodeEx+0x9b
python39.dll!PyEval_EvalCode+0x2d
Blender Launcher Updater.exe+0x26cf
Blender Launcher Updater.exe+0x2bb1
Blender Launcher Updater.exe+0x888e
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

It also spawns some other threads, but they look like housekeeping to my untrained eye.

```
ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
ntdll.dll!TpReleaseCleanupGroupMembers+0x747
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

I tried it a few more times, sometimes it hangs indefinitely, sometimes it exits very quickly. Also tested it on my NTFS file system, it behaves the same way there.

**Comment by DotBow** [comment]
Could you please run the DEBUG version with fake 1.10.0 version just to trace the issue?

https://drive.google.com/file/d/1NLtdAP5Fc_uA_VjTLZmpRJUr7nawcUrD/view?usp=sharing

**Comment by brunnerh** [comment]
Well, for that file the update works without problems 😅

Log entries:

```log
2021-09-11 19:41:45,026 - Starting new HTTPS connection (1): github.com:443
2021-09-11 19:41:45,122 - https://github.com:443 "GET /DotBow/Blender-Launcher/releases/latest HTTP/1.1" 302 129
2021-09-11 19:41:45,122 - Incremented Retry for (url='https://github.com/DotBow/Blender-Launcher/releases/latest'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2021-09-11 19:41:45,122 - Redirecting https://github.com/DotBow/Blender-Launcher/releases/latest -> https://github.com/DotBow/Blender-Launcher/releases/tag/v1.14.0
2021-09-11 19:41:45,147 - https://github.com:443 "GET /DotBow/Blender-Launcher/releases/tag/v1.14.0 HTTP/1.1" 200 None
```
